/**
 * Forge Batch — companies first tech products origin stories
 * 
 * Generated: 2026-06-07
 * Import: npx tsx scripts/forge/2_import_batch.ts scripts/forge/batches/batch_companies_origin_stories.ts
 */
import type { QuizGambitQuestion } from '../../src/lib/ai/types';

function q(lens: string, form: string, questionText: string, answerText: string,
  options: [string, string, string, string], backdoorType: string, backdoorExplanation: string,
  points: number, difficultyTier: string, tag?: string): QuizGambitQuestion {
  return { lens, form, question_text: questionText, answer_text: answerText,
    options, backdoor_type: backdoorType, backdoor_explanation: backdoorExplanation,
    points, difficulty_tier: difficultyTier, tag } as QuizGambitQuestion;
}

function cat(name: string, mainCategory: string, description: string,
  lensMode: 'diverse' | 'focused', targetLens: string | undefined,
  questions: QuizGambitQuestion[], tags: string[] = []) {
  return { name, main_category: mainCategory, description,
    lens_mode: lensMode, target_lens: targetLens, data: questions, tags };
}

export const batch = [cat(
  'companies first tech products origin stories',
  'Technology',
  'Focused on Origin Story — how tech companies created their breakthrough first products',
  'focused',
  'Origin Story',
  [
    q('Origin Story', 'Form 5 (Direct Narrative)',
      'Scrambling to meet payroll in 1976, two college dropouts hand-built 50 units of this wooden-cased machine in a garage, selling them for $666.66 each to a local hobbyist shop.',
      'Apple I',
      ['Apple I', 'Altair 8800', 'Commodore PET', 'TRS-80'],
      'Everyday Link',
      'The garage origin + college dropouts + 1976 firmly point to Apple. The $666.66 price is a well-known quirky detail of the Apple I.',
      100, 'easy', 'Apple'),

    q('Origin Story', 'Form 2 (Parenthetical Hook)',
      'Unlike the sleek social network it would become, this company\'s first product was a website called "Facemash" — a hot-or-not rating game that scraped Harvard dorm photos without permission and nearly got its founder expelled.',
      'Facebook (Meta)',
      ['Facebook (Meta)', 'MySpace', 'Friendster', 'LinkedIn'],
      'Contrast Pop',
      'Facemash is the infamous Harvard origin story unique to Zuckerberg. The "nearly got expelled" detail is unmistakably Facebook.',
      200, 'easy', 'Meta'),

    q('Origin Story', 'Form 1 (Action-First)',
      'Pivoting from a failing podcasting platform called Odeo, this company gave its employees a two-week hackathon that produced a side project allowing users to broadcast 140-character status updates to the world.',
      'Twitter (X)',
      ['Twitter (X)', 'Tumblr', 'Reddit', 'Medium'],
      'Everyday Link',
      'Odeo → podcasting failure → 140 characters = Twitter\'s well-documented origin story. No other major platform started as a podcasting company.',
      200, 'easy', 'Twitter'),

    q('Origin Story', 'Form 8 (The Timeline)',
      'First conceived in 1996 as "BackRub" — a research project that ranked pages by counting backlinks — this search engine operated from a Stanford dorm room before its founders tried to sell it for $1 million in 1999, only to be rejected by every major tech company.',
      'Google',
      ['Google', 'Yahoo', 'AltaVista', 'Ask Jeeves'],
      'Sequence Pattern',
      'BackRub → backlinks → Stanford → $1M sale attempt in 1999 = unmistakably Google\'s origin. The timeline and dorm room detail are unique.',
      100, 'easy', 'Google'),

    q('Origin Story', 'Form 4 (Active Quote)',
      '"We will crush Netscape," a young Bill Gates allegedly declared before this 1995 web browser — bundled free with every Windows 95 installation — ignited the browser wars and triggered a landmark antitrust case against the company.',
      'Internet Explorer',
      ['Internet Explorer', 'Netscape Navigator', 'Opera', 'Mozilla Firefox'],
      'Pop Culture Hook',
      '"Crush Netscape" quote + Windows 95 bundling + antitrust = unmistakably Internet Explorer. The browser wars are one of tech history\'s most famous rivalries.',
      300, 'medium', 'Microsoft'),

    q('Origin Story', 'Form 5 (Direct Narrative)',
      'In 2007, a struggling video game company called Tiny Speck built an internal messaging tool to coordinate their remote team across four cities — when their game Glitch failed, they pivoted entirely to this chat platform, which now powers millions of remote workplaces.',
      'Slack',
      ['Slack', 'Discord', 'Microsoft Teams', 'Zoom'],
      'Functional Logic',
      'Tiny Speck → Glitch game → internal chat tool pivot = Slack\'s unique origin. No other workplace chat app was born from a failed MMO game company.',
      300, 'medium', 'Slack'),

    q('Origin Story', 'Form 6 (The Contradiction)',
      'Despite being the world\'s largest video platform today, this company\'s original concept in 2005 was a video-based dating site where users uploaded clips of themselves describing their ideal partner — a concept so unpopular the founders began uploading random videos just to keep the site alive.',
      'YouTube',
      ['YouTube', 'Vimeo', 'Dailymotion', 'Twitch'],
      'Contrast Pop',
      'Video dating site origin → pivoted to general videos = YouTube\'s famous origin story. The "upload random videos to keep it alive" detail is iconic.',
      200, 'easy', 'YouTube'),

    q('Origin Story', 'Form 3 (Sensory Clue)',
      'Vibrant red with a retro-chrome interface, this company\'s debut product in 2007 was a boxy DVD-by-mail rental machine that streamed content to your TV for a flat monthly fee, killing the video rental industry practically overnight.',
      'Netflix (Roku partnership)',
      ['Netflix (Roku partnership)', 'Blockbuster On Demand', 'TiVo', 'Apple TV'],
      'Sensory Logic',
      '"DVD-by-mail rental" + 2007 launch + killed video rental = Netflix. The Roku was originally developed inside Netflix as "Project Griffin."',
      400, 'challenging', 'Netflix'),

    q('Origin Story', 'Form 7 (The Question Lead)',
      'A frustrated computer science student misspelled his favorite Futurama character to name a file-sharing service in 1999 — then every major record label sued him simultaneously, forcing the platform to eventually become a legitimate business that paid billions to the music industry.',
      'Napster',
      ['Napster', 'Kazaa', 'LimeWire', 'BitTorrent'],
      'Etymology / Name Logic',
      'Futurama character misspelling + 1999 + sued by all record labels = unmistakably Napster (Shawn Fanning). The Futurama reference is the key etymology clue.',
      300, 'medium', 'Napster'),

    q('Origin Story', 'Form 10 (Defining Trait)',
      'Anonymous, ephemeral, and originally designed as a disappearing-photo-sharing app for college parties, this company\'s first prototype was built in a Stanford dorm and rejected by every investor until one partner\'s teenage daughter declared it her favorite app.',
      'Snapchat',
      ['Snapchat', 'Instagram Stories', 'Telegram', 'WhatsApp'],
      'Everyday Link',
      'Disappearing photos + Stanford dorm + teenage daughter approved = Snapchat\'s origin. The ephemeral nature is the defining trait that sets it apart.',
      200, 'easy', 'Snapchat'),

    q('Origin Story', 'Form 5 (Direct Narrative)',
      'In 1994, a programmer quit his hedge fund job, drove across the country to Seattle, and began selling books from his garage through a site originally called "Cadabra" — until his lawyer misheard it as "cadaver" and insisted on a name that evokes something vast, exotic, and unstoppable.',
      'Amazon',
      ['Amazon', 'eBay', 'Barnes & Noble Online', 'Overstock'],
      'Etymology / Name Logic',
      'Cadabra → cadaver mishearing → vast/exotic/unstoppable name = Amazon (Jeff Bezos). The lawyer mishearing story is a well-known origin detail.',
      100, 'easy', 'Amazon'),

    q('Origin Story', 'Form 2 (Parenthetical Hook)',
      'Unlike every other messaging app that required a phone number and a friend list, this company\'s first product let users chat with complete strangers based on shared interests — a 17-year-old Russian dropout built it in his bedroom and sold it to a New York investor for a stake that would later be worth billions.',
      'Telegram',
      ['Telegram', 'WhatsApp', 'Signal', 'WeChat'],
      'Contrast Pop',
      'Russian dropout + bedroom coding + sold to investor = Pavel Durov and Telegram\'s origin. The no-phone-number-needed is a key differentiator.',
      300, 'medium', 'Telegram'),

    q('Origin Story', 'Form 8 (The Timeline)',
      'First prototyped in a San Francisco loft in 2007, this company\'s founders couldn\'t afford rent so they rented out air mattresses on their living room floor during a design conference — photographing the "guests" eating breakfast cereal and calling their experiment "AirBed & Breakfast" before renaming it in 2009.',
      'Airbnb',
      ['Airbnb', 'Couchsurfing', 'VRBO', 'HomeAway'],
      'Everyday Link',
      'Air mattresses + design conference + "AirBed & Breakfast" + 2009 rename = Airbnb (Brian Chesky and Joe Gebbia). The cereal box funding story is iconic.',
      200, 'easy', 'Airbnb'),

    q('Origin Story', 'Form 1 (Action-First)',
      'Desperate for a name that would alphabetically appear before "Apple" in the phone book, two former audio-equipment engineers registered their company in a Palo Alto garage in 1939 — the toss of a coin determined whether the company would be named after one founder or the other.',
      'Hewlett-Packard (HP)',
      ['Hewlett-Packard (HP)', 'Intel', 'Fairchild Semiconductor', 'Xerox PARC'],
      'Functional Logic',
      '1939 Palo Alto garage + coin toss between Hewlett and Packard + alphabetically before Apple = Hewlett-Packard. Their first product was an audio oscillator sold to Walt Disney.',
      200, 'easy', 'HP'),

    q('Origin Story', 'Form 6 (The Contradiction)',
      'Despite being founded by a man who couldn\'t code, this company\'s first product was a simple HTML-based website builder launched from a San Francisco apartment in 2004 — the founder taught himself programming at night while working as a customer support agent during the day.',
      'Wix',
      ['Wix', 'Squarespace', 'Weebly', 'WordPress.com'],
      'Everyday Link',
      'Couldn\'t code → taught himself at night → HTML website builder from apartment = Wix\'s story. The support-agent-by-day detail is unique.',
      400, 'challenging', 'Wix'),

    q('Origin Story', 'Form 7 (The Question Lead)',
      'A Canadian teenager tinkering alone in his bedroom in 2002 built a bare-bones PHP script originally called "Pictorial" — that side project evolved into a platform where millions now share their deepest confessions entirely anonymously, with no profiles, no followers, and no usernames whatsoever.',
      'Whisper',
      ['Whisper', 'Secret', 'Yik Yak', 'PostSecret'],
      'Etymology / Name Logic',
      'No profiles + no followers + no usernames + anonymous confessions + Canadian teenager = Whisper. The Pictorial-to-Whisper pivot is a lesser-known origin story.',
      500, 'expert', 'Whisper'),

    q('Origin Story', 'Form 4 (Active Quote)',
      '"Let\'s just build something people want," said a former Apple engineer to his co-founder as they launched this company\'s first product in 2009 — a tiny square card reader that plugged into the headphone jack of an iPhone, enabling anyone to accept credit card payments anywhere.',
      'Square',
      ['Square', 'Stripe', 'PayPal Here', 'Clover'],
      'Pop Culture Hook',
      'Former Apple engineer + 2009 + headphone jack card reader = Square (Jack Dorsey and Jim McKelvey). The "anyone can accept payments" democratization is Square\'s mission.',
      300, 'medium', 'Square'),

    q('Origin Story', 'Form 3 (Sensory Clue)',
      'Metallic grey with a distinctive circular scroll wheel, this company\'s debut music player in 2001 stored a thousand songs in your pocket and was so radically simple that reviewers initially called it a "lame product" — before it went on to save the entire company from irrelevance.',
      'iPod',
      ['iPod', 'Zune', 'Creative Nomad', 'Rio PMP300'],
      'Sensory Logic',
      'Metallic grey + scroll wheel + 1000 songs in your pocket + 2001 + saved the company = iPod. The "lame product" initial reviews are a famous part of its origin.',
      200, 'easy', 'Apple'),

    q('Origin Story', 'Form 5 (Direct Narrative)',
      'In 1998, two Stanford PhD students set out to build a better search engine but first created a side project that organized the entire internet into a hierarchical directory of links — hiring actual human editors to categorize every website on the nascent World Wide Web.',
      'Yahoo Directory',
      ['Yahoo Directory', 'DMOZ', 'Google Directory', 'LookSmart'],
      'Functional Logic',
      'Two Stanford PhDs + 1998 + human editors organizing web into directories = Yahoo, founded by Jerry Yang and David Filo as "Jerry and David\'s Guide to the World Wide Web."',
      300, 'medium', 'Yahoo'),

    q('Origin Story', 'Form 10 (Defining Trait)',
      'Open-source, community-driven, and built by a 21-year-old Finnish student who just wanted to access his university\'s UNIX servers from home, this operating system kernel was released in 1991 with a famously humble announcement: "just a hobby, won\'t be big and professional."',
      'Linux',
      ['Linux', 'FreeBSD', 'Minix', 'GNU Hurd'],
      'Etymology / Name Logic',
      '21-year-old Finnish student + 1991 + "just a hobby" + UNIX servers from home = Linus Torvalds and Linux. The humble announcement is one of tech history\'s most famous posts.',
      200, 'easy', 'Linux'),

    q('Origin Story', 'Form 2 (Parenthetical Hook)',
      'Unlike most billion-dollar startups that began in Silicon Valley, this company\'s first product was conceived in a Delaware Taco Bell parking lot where two engineers sketched out a simple API for processing credit card payments — the entire prototype was just seven lines of code.',
      'Stripe',
      ['Stripe', 'Braintree', 'Square', 'Adyen'],
      'Contrast Pop',
      'Taco Bell parking lot + seven lines of code + simple payment API = Stripe\'s legendary origin. The Collison brothers\' minimalist approach is the core contrast.',
      100, 'easy', 'Stripe'),

    q('Origin Story', 'Form 8 (The Timeline)',
      'First released in 2003 as a plugin for the Winamp media player, then ported to Windows in 2004, acquired by a Swedish company in 2006, and finally relaunched as a standalone streaming service in 2008 — this music platform now accounts for over 30% of all global music industry revenue.',
      'Spotify',
      ['Spotify', 'Pandora', 'Apple Music', 'Deezer'],
      'Sequence Pattern',
      '2003 Winamp plugin → 2008 streaming launch → Swedish company → 30% of global music revenue = Spotify (Daniel Ek and Martin Lorentzon). The acquisition timeline is unique.',
      200, 'easy', 'Spotify'),

    q('Origin Story', 'Form 1 (Action-First)',
      'Frustrated by the unreliable taxi service in Paris on a snowy evening in 2008, two entrepreneurs couldn\'t find a cab and asked themselves: what if you could summon a private driver with the tap of a button — launching a ride-hailing service that would eventually operate in over 900 metropolitan areas worldwide.',
      'Uber',
      ['Uber', 'Lyft', 'Bolt', 'Gett'],
      'Everyday Link',
      'Paris + snowy evening + couldn\'t find a cab + 2008 = Uber\'s classic origin story. The "tap of a button" convenience premise was revolutionary.',
      100, 'easy', 'Uber'),

    q('Origin Story', 'Form 6 (The Contradiction)',
      'Despite being known today as a photo-sharing giant, this company began as a feature inside a failed multiplayer online game called "Game Neverending" — developed by a small Vancouver studio in 2004, the game flopped but its real-time photo-sharing tool was so compelling that the entire company pivoted to build an independent platform around it.',
      'Flickr',
      ['Flickr', 'DeviantArt', 'Photobucket', 'Imgur'],
      'Functional Logic',
      'Vancouver studio + 2004 + "Game Neverending" + photo-sharing pivot = Flickr (Ludicorp, later acquired by Yahoo). The game-to-photo-app evolution is unique.',
      500, 'expert', 'Flickr'),

    q('Origin Story', 'Form 7 (The Question Lead)',
      'A Ukrainian immigrant who grew up without hot water and relied on food stamps taught himself programming from used bookstore manuals — in 2009, inspired by the 160-character limit of his old Nokia phone\'s SMS, he built a messaging app so addictive that within months it was processing more messages per day than the entire global SMS network combined.',
      'WhatsApp',
      ['WhatsApp', 'Telegram', 'Signal', 'WeChat'],
      'Functional Logic',
      'Ukrainian immigrant + food stamps + self-taught from used books + 160-char SMS limit + 2009 + more than global SMS = WhatsApp (Jan Koum). The rags-to-riches origin is inspirational.',
      400, 'challenging', 'WhatsApp'),

    q('Origin Story', 'Form 4 (Active Quote)',
      '"I think there is a world market for maybe five computers," a technology executive allegedly declared in 1943 — completely missing that his own company would launch the 1981 machine that standardized personal computing for an entire generation, running an operating system licensed from a tiny startup called Microsoft.',
      'IBM PC',
      ['IBM PC', 'Apple II', 'Commodore 64', 'Atari 800'],
      'Pop Culture Hook',
      '"World market for maybe five computers" + 1981 + Microsoft OS = the IBM PC. The infamous misquote is attributed to IBM chairman Thomas Watson.',
      200, 'easy', 'IBM'),

    q('Origin Story', 'Form 3 (Sensory Clue)',
      'Encased in translucent Bondi blue plastic that made it look more like a candy dispenser than a computer, this company\'s 1998 all-in-one desktop was the first product launched after its exiled founder returned to save the company from near-bankruptcy, redefining consumer electronics design forever.',
      'iMac G3',
      ['iMac G3', 'Dell WebPC', 'Compaq Presario', 'eMachines'],
      'Sensory Logic',
      'Bondi blue translucent plastic + 1998 + exiled founder returns + near-bankruptcy = iMac G3 and Steve Jobs\' return to Apple. The candy-like design was revolutionary.',
      100, 'easy', 'Apple'),

    q('Origin Story', 'Form 5 (Direct Narrative)',
      'In 1984, a former Harvard Business School student compiled a list of 189 friends and business contacts onto a printed directory he called "The Address Book" — distributing physical copies at networking events in Manhattan before digitizing it into a professional networking website in 2003 that would eventually connect over 900 million professionals worldwide.',
      'LinkedIn',
      ['LinkedIn', 'Plaxo', 'Ryze', 'Xing'],
      'Everyday Link',
      'Harvard Business School + printed address book + 2003 digitization + 900M professionals = LinkedIn (Reid Hoffman). The physical-directory-to-digital-network origin is unique.',
      300, 'medium', 'LinkedIn'),

    q('Origin Story', 'Form 2 (Parenthetical Hook)',
      'Unlike most browsers that were built by massive corporations, this one was created by a single developer in 2004 who forked an existing open-source project because he was annoyed by pop-up ads — naming his browser after a swift Arctic predator and a graphical rendering engine.',
      'Firefox',
      ['Firefox', 'Opera', 'Brave', 'Safari'],
      'Etymology / Name Logic',
      'Single developer + 2004 + forked from open source + annoyed by pop-ups + Arctic predator name = Firefox (originally Phoenix, then Firebird, then Firefox for trademark reasons).',
      300, 'medium', 'Mozilla'),

    q('Origin Story', 'Form 1 (Action-First)',
      'Aiming to eliminate the frustration of paper business cards at tech conferences, a team of engineers built a prototype in 2002 that allowed two Palm Pilots to exchange contact information by physically tapping them together — a Bluetooth-powered handshake that predated smartphones and modern contact-sharing by over a decade.',
      'Bump',
      ['Bump', 'Poken', 'Drop', 'Beam'],
      'Functional Logic',
      '2002 + Palm Pilots + physical tap to exchange + Bluetooth handshake + predated smartphones = Bump Technologies (later acquired by Google). The pre-iPhone era timing is the giveaway.',
      500, 'expert', 'Bump'),
  ],
  ['Grid', 'Technology', 'companies first tech products origin stories', 'Lens:Origin Story', 'Mode:Focused']
)];

export const meta = {
  generatedAt: '2026-06-07T17:14:00.000Z',
  batchNumber: 1,
  mode: 'focused' as const,
};
