/**
 * Forge Batch: Geography — 5 Focused Topics, 30 Questions Each
 * 
 * Focused mode: all 30 questions per topic share the same lens, form, backdoor.
 * Total: 150 questions across 5 topics.
 */

import type { QuizGambitQuestion } from '../../src/lib/ai/types';

function q(
  lens: string,
  form: string,
  questionText: string,
  answerText: string,
  options: [string, string, string, string],
  backdoorType: string,
  backdoorExplanation: string,
  points: number,
  difficultyTier: string,
  tag?: string,
): QuizGambitQuestion {
  return {
    lens, form, question_text: questionText, answer_text: answerText,
    options, backdoor_type: backdoorType, backdoor_explanation: backdoorExplanation,
    points, difficulty_tier: difficultyTier, tag,
  } as QuizGambitQuestion;
}

function cat(
  name: string,
  mainCategory: string,
  description: string,
  lensMode: 'diverse' | 'focused',
  targetLens: string | undefined,
  questions: QuizGambitQuestion[],
  tags: string[] = [],
) {
  return { name, main_category: mainCategory, description, lens_mode: lensMode, target_lens: targetLens, data: questions, tags };
}

// ═══════════════════════════════════════════════════════════════════
// TOPIC 1: World Capitals (Lens: The Connection)
// ═══════════════════════════════════════════════════════════════════

const topic1 = cat(
  'World Capitals: The City-Country Connection',
  'Geography',
  'Test your knowledge of capital cities across every continent — from the obvious to the obscure.',
  'focused',
  'The Connection',
  [
    // ── Easy (1-10): 100 pts ──
    q('The Connection', 'Form 5 (Direct Narrative)',
      'This city, built on seven hills along the Tiber River, serves as the capital of Italy and houses an independent city-state within its borders.',
      'Rome',
      ['Rome', 'Athens', 'Madrid', 'Vienna'],
      'Category Elimination',
      'Only Rome sits on the Tiber River among these options. Athens is in Greece, Madrid in Spain, Vienna in Austria.',
      100, 'easy', 'Seven hills'),
    q('The Connection', 'Form 5 (Direct Narrative)',
      'Located on the Seine River, this European capital is known as the "City of Light" and is home to the Eiffel Tower, the Louvre, and Notre-Dame Cathedral.',
      'Paris',
      ['Paris', 'London', 'Berlin', 'Brussels'],
      'Category Elimination',
      'The Seine River, Eiffel Tower, and Louvre are unmistakably Paris. London has the Thames; Berlin has the Spree; Brussels has the Senne.',
      100, 'easy', 'City of Light'),
    q('The Connection', 'Form 5 (Direct Narrative)',
      'This Asian capital was once called Edo and is the most populous metropolitan area in the world, blending ancient temples with neon-lit skyscrapers.',
      'Tokyo',
      ['Tokyo', 'Seoul', 'Beijing', 'Bangkok'],
      'Category Elimination',
      'Edo was renamed Tokyo in 1868. Seoul was Hanyang, Beijing was Peking, and Bangkok was never called Edo.',
      100, 'easy', 'Edo'),
    q('The Connection', 'Form 5 (Direct Narrative)',
      'This capital of Egypt sits on the banks of the Nile River and is the largest city in Africa and the Arab world.',
      'Cairo',
      ['Cairo', 'Nairobi', 'Lagos', 'Khartoum'],
      'Category Elimination',
      'Cairo is Egypt\'s capital on the Nile. Nairobi is Kenya\'s capital, Lagos is not Nigeria\'s capital (Abuja is), and Khartoum is Sudan\'s capital.',
      100, 'easy', 'Nile'),
    q('The Connection', 'Form 5 (Direct Narrative)',
      'This South American capital sits at an elevation of 2,640 meters and is the highest administrative capital in the world, located in the Andes Mountains.',
      'La Paz',
      ['La Paz', 'Quito', 'Bogotá', 'Lima'],
      'Category Elimination',
      'La Paz, Bolivia sits at 2,640m — the highest capital. Quito is at 2,850m but is not the administrative capital (Sucre is Bolivia\'s constitutional capital).',
      100, 'easy', 'Highest'),
    q('The Connection', 'Form 5 (Direct Narrative)',
      'This capital of Canada sits on the Ottawa River, was chosen by Queen Victoria in 1857, and is home to Parliament Hill.',
      'Ottawa',
      ['Ottawa', 'Toronto', 'Montreal', 'Vancouver'],
      'Category Elimination',
      'Ottawa was specifically chosen as a compromise capital between Toronto and Montreal. Vancouver has never been the capital.',
      100, 'easy', 'Queen Victoria'),
    q('The Connection', 'Form 5 (Direct Narrative)',
      'This capital of Australia was purpose-built as a compromise between Sydney and Melbourne, designed by American architect Walter Burley Griffin.',
      'Canberra',
      ['Canberra', 'Sydney', 'Melbourne', 'Brisbane'],
      'Category Elimination',
      'Canberra was built specifically to be the capital after the Federation of Australia in 1901. Neither Sydney nor Melbourne got the title.',
      100, 'easy', 'Compromise'),
    q('The Connection', 'Form 5 (Direct Narrative)',
      'This Nordic capital is spread across 14 islands where Lake Mälaren meets the Baltic Sea, earning it the nickname "Venice of the North."',
      'Stockholm',
      ['Stockholm', 'Copenhagen', 'Oslo', 'Helsinki'],
      'Category Elimination',
      'Stockholm\'s archipelago geography across Lake Mälaren is unique among Nordic capitals. Copenhagen is on islands too but not at a lake-sea junction.',
      100, 'easy', '14 islands'),
    q('The Connection', 'Form 5 (Direct Narrative)',
      'This capital of Argentina sits on the Río de la Plata estuary and is known for its European-style architecture, tango, and the colorful La Boca neighborhood.',
      'Buenos Aires',
      ['Buenos Aires', 'Santiago', 'Montevideo', 'Lima'],
      'Category Elimination',
      'Buenos Aires is Argentina\'s capital on the Río de la Plata. Santiago is Chile\'s capital inland, Montevideo is Uruguay\'s capital, Lima is Peru\'s.',
      100, 'easy', 'Tango'),
    q('The Connection', 'Form 5 (Direct Narrative)',
      'This capital of Thailand is known in Thai as Krung Thep Maha Nakhon and holds the Guinness World Record for the longest place name.',
      'Bangkok',
      ['Bangkok', 'Hanoi', 'Phnom Penh', 'Yangon'],
      'Category Elimination',
      'Bangkok\'s ceremonial name has 168 letters. The other cities are capitals of Vietnam, Cambodia, and Myanmar respectively.',
      100, 'easy', 'Longest name'),

    // ── Medium (11-20): 300 pts ──
    q('The Connection', 'Form 5 (Direct Narrative)',
      'This capital of Kazakhstan was briefly renamed Nur-Sultan (2019-2022) to honor its first president, then reverted to Astana — making it one of the few capitals to regain its original name.',
      'Astana',
      ['Astana', 'Almaty', 'Tashkent', 'Bishkek'],
      'Category Elimination',
      'Astana was renamed in 2019 from Astana to honor Nursultan Nazarbayev (renamed back to Astana in 2022). Almaty was the previous capital, Tashkent is Uzbekistan\'s capital, Bishkek is Kyrgyzstan\'s.',
      300, 'medium', 'Renamed'),
    q('The Connection', 'Form 5 (Direct Narrative)',
      'This capital of Myanmar was purpose-built in the early 2000s and replaced Yangon, though its exact purpose remains shrouded in mystery.',
      'Naypyidaw',
      ['Naypyidaw', 'Yangon', 'Mandalay', 'Bangkok'],
      'Category Elimination',
      'Naypyidaw became the capital in 2005-2006, a planned city with wide highways but very few residents. Yangon was the former capital.',
      300, 'medium', 'Planned city'),
    q('The Connection', 'Form 5 (Direct Narrative)',
      'This African capital was founded by the French in 1859 on a peninsula and is one of the few world capitals named after a European explorer.',
      'Brazzaville',
      ['Brazzaville', 'Kinshasa', 'Libreville', 'Bamako'],
      'Category Elimination',
      'Brazzaville (Republic of Congo) was named after Pierre Savorgnan de Brazza. Kinshasa is directly across the Congo River. Libreville means "Free Town."',
      300, 'medium', 'Explorer'),
    q('The Connection', 'Form 5 (Direct Narrative)',
      'This is the capital of Sri Lanka, though its largest city Colombo is often mistaken for the capital. It was designated as the administrative capital in 1982.',
      'Sri Jayawardenepura Kotte',
      ['Sri Jayawardenepura Kotte', 'Colombo', 'Kandy', 'Galle'],
      'Category Elimination',
      'Sri Jayawardenepura Kotte is the legislative capital since 1982. Colombo remains the commercial capital. Kandy was the last Sinhalese kingdom.',
      300, 'medium', 'Mistaken identity'),
    q('The Connection', 'Form 5 (Direct Narrative)',
      'This tiny European capital is one of the smallest in the world by population, with fewer than 6,000 residents, yet it governs an entire country from a medieval castle.',
      'Vaduz',
      ['Vaduz', 'San Marino', 'Valletta', 'Luxembourg City'],
      'Category Elimination',
      'Vaduz, Liechtenstein has ~5,700 residents (not under 600, but one of the smallest). San Marino city has ~4,000. Valletta has ~6,000. Luxembourg City is larger.',
      300, 'medium', 'Smallest'),
    q('The Connection', 'Form 5 (Direct Narrative)',
      'This South American capital is the only world capital located directly on the equator, marked by the Mitad del Mundo monument.',
      'Quito',
      ['Quito', 'Bogotá', 'Lima', 'La Paz'],
      'Category Elimination',
      'Quito, Ecuador sits just south of the equator. The Mitad del Mundo monument marks the equatorial line. Bogotá is north of the equator.',
      300, 'medium', 'Equator'),
    q('The Connection', 'Form 5 (Direct Narrative)',
      'This capital of Bhutan is located in a Himalayan valley at 2,320 meters and has no traffic lights — traffic is directed by hand by police officers.',
      'Thimphu',
      ['Thimphu', 'Kathmandu', 'Paro', 'Gangtok'],
      'Category Elimination',
      'Thimphu famously has no traffic lights. Kathmandu is Nepal\'s capital. Paro is a city in Bhutan but not the capital. Gangtok is in India.',
      300, 'medium', 'No traffic lights'),
    q('The Connection', 'Form 5 (Direct Narrative)',
      'This island capital sits on a harbor formed by a drowned volcanic crater and is the smallest national capital in the European Union by area.',
      'Valletta',
      ['Valletta', 'Nicosia', 'Luxembourg City', 'Dublin'],
      'Category Elimination',
      'Valletta, Malta is the smallest EU capital by area at 0.8 km². It sits on the Grand Harbour, a natural deep-water port.',
      300, 'medium', 'Volcanic harbor'),
    q('The Connection', 'Form 5 (Direct Narrative)',
      'This capital of Burkina Faso was named after a local chief and means "the place of honest men" in the Mossi language.',
      'Ouagadougou',
      ['Ouagadougou', 'Bamako', 'Niamey', 'Abuja'],
      'Category Elimination',
      'Ouagadougou means "place of honest men" in Mossi. Bamako is Mali\'s capital, Niamey is Niger\'s, Abuja is Nigeria\'s.',
      300, 'medium', 'Honest men'),
    q('The Connection', 'Form 5 (Direct Narrative)',
      'This capital of Fiji sits on the southeastern coast of Viti Levu island and is the largest city in the South Pacific outside Australia and New Zealand.',
      'Suva',
      ['Suva', 'Nadi', 'Apia', 'Port Moresby'],
      'Category Elimination',
      'Suva, Fiji is the South Pacific\'s major hub. Nadi is Fiji\'s tourist gateway. Apia is Samoa\'s capital. Port Moresby is PNG\'s capital.',
      300, 'medium', 'Viti Levu'),

    // ── Challenging (21-25): 400 pts ──
    q('The Connection', 'Form 5 (Direct Narrative)',
      'This capital of Suriname sits on the Suriname River just 15 km from the Atlantic Ocean and is home to a historic inner city that is a UNESCO World Heritage site.',
      'Paramaribo',
      ['Paramaribo', 'Georgetown', 'Cayenne', 'Brasília'],
      'Category Elimination',
      'Paramaribo\'s historic center is UNESCO-listed for its Dutch colonial architecture. Georgetown is Guyana\'s capital, Cayenne is French Guiana\'s.',
      400, 'challenging', 'UNESCO'),
    q('The Connection', 'Form 5 (Direct Narrative)',
      'This capital of Tajikistan was named "Monday" in the local language because of the famous market that took place there on that day.',
      'Dushanbe',
      ['Dushanbe', 'Tashkent', 'Bishkek', 'Ashgabat'],
      'Category Elimination',
      'Dushanbe means "Monday" in Tajik/Persian. Tashkent is Uzbekistan\'s capital, Bishkek is Kyrgyzstan\'s, Ashgabat is Turkmenistan\'s.',
      400, 'challenging', 'Monday'),
    q('The Connection', 'Form 5 (Direct Narrative)',
      'This capital of Eswatini was named after a British colonial administrator and is one of the few capitals in the world whose name means "place of the king" in the local siSwati language.',
      'Mbabane',
      ['Mbabane', 'Maseru', 'Gaborone', 'Maputo'],
      'Category Elimination',
      'Mbabane is the administrative capital of Eswatini (formerly Swaziland). Maseru is Lesotho\'s capital, Gaborone is Botswana\'s, Maputo is Mozambique\'s.',
      400, 'challenging', 'Eswatini'),
    q('The Connection', 'Form 5 (Direct Narrative)',
      'This capital of Palau was relocated from Koror in 2006 and sits on Babeldaob, the country\'s largest island, yet has a population of fewer than 400 people.',
      'Ngerulmud',
      ['Ngerulmud', 'Koror', 'Majuro', 'Palikir'],
      'Category Elimination',
      'Ngerulmud became Palau\'s capital in 2006. Koror is the former capital and largest city. Majuro is Marshall Islands\' capital, Palikir is Micronesia\'s.',
      400, 'challenging', '400 people'),
    q('The Connection', 'Form 5 (Direct Narrative)',
      'This capital of Equatorial Guinea was built from scratch on the mainland in the 2010s as a planned city, replacing Malabo on Bioko Island.',
      'Ciudad de la Paz',
      ['Ciudad de la Paz', 'Malabo', 'Bata', 'Libreville'],
      'Category Elimination',
      'Ciudad de la Paz (formerly Oyala) is the planned new capital of Equatorial Guinea. Malabo is the current de facto capital on Bioko Island.',
      400, 'challenging', 'Planned replacement'),

    // ── Expert (26-30): 500 pts ──
    q('The Connection', 'Form 5 (Direct Narrative)',
      'This is the capital of São Tomé and Príncipe, an island nation off the coast of Central Africa, and its name means "Saint Thomas" in Portuguese.',
      'São Tomé',
      ['São Tomé', 'Praia', 'Bissau', 'Luanda'],
      'Category Elimination',
      'São Tomé is both the capital and name of the main island. Praia is Cape Verde\'s capital, Bissau is Guinea-Bissau\'s, Luanda is Angola\'s.',
      500, 'expert', 'Saint Thomas'),
    q('The Connection', 'Form 5 (Direct Narrative)',
      'This capital of the Solomon Islands was the site of fierce fighting during World War II\'s Guadalcanal campaign and is named after a British naval officer.',
      'Honiara',
      ['Honiara', 'Port Vila', 'Suva', 'Nuku\'alofa'],
      'Category Elimination',
      'Honiara\'s name originates from a local word but the town grew around Henderson Field, named after a US aviator. Port Vila is Vanuatu\'s capital.',
      500, 'expert', 'Guadalcanal'),
    q('The Connection', 'Form 5 (Direct Narrative)',
      'This capital of Djibouti shares its name with the country itself and sits on the Gulf of Tadjoura, serving as the primary port for landlocked Ethiopia.',
      'Djibouti City',
      ['Djibouti City', 'Mogadishu', 'Asmara', 'Addis Ababa'],
      'Category Elimination',
      'Djibouti City is the capital of Djibouti, a major port for Ethiopian trade. Mogadishu is Somalia\'s capital, Asmara is Eritrea\'s, Addis Ababa is Ethiopia\'s.',
      500, 'expert', 'City-country same'),
    q('The Connection', 'Form 5 (Direct Narrative)',
      'This capital of the Comoros sits on the largest island of the archipelago, Grande Comore, and its name means "in the heart of the fire" in Arabic, referencing the active volcano Mount Karthala.',
      'Moroni',
      ['Moroni', 'Antananarivo', 'Port Louis', 'Victoria'],
      'Category Elimination',
      'Moroni is at the foot of Mount Karthala. Antananarivo is Madagascar\'s capital, Port Louis is Mauritius\'s, Victoria is Seychelles\'.',
      500, 'expert', 'Heart of fire'),
    q('The Connection', 'Form 5 (Direct Narrative)',
      'This capital of Kiribati sits on the atoll of Tarawa and was the site of one of the bloodiest battles in the Pacific during World War II — the Battle of Tarawa in 1943.',
      'South Tarawa',
      ['South Tarawa', 'Funafuti', 'Majuro', 'Yaren'],
      'Category Elimination',
      'South Tarawa is Kiribati\'s capital on Tarawa Atoll. Funafuti is Tuvalu\'s capital, Majuro is Marshall Islands\', Yaren is Nauru\'s.',
      500, 'expert', 'Tarawa'),
  ],
  ['Grid', 'World Capitals: The City-Country Connection', 'Theme:Geography', 'Human', 'Facts', 'Classic', 'Mode:Focused', 'AI:Suggested'],
);

// ═══════════════════════════════════════════════════════════════════
// TOPIC 2: Flags of the World (Lens: The Oddity)
// ═══════════════════════════════════════════════════════════════════

const topic2 = cat(
  'Flags of the World: Decoding National Symbols',
  'Geography',
  'Identify countries by the hidden meanings, colors, and symbols woven into their national flags.',
  'focused',
  'The Oddity',
  [
    // ── Easy (1-10): 100 pts ──
    q('The Oddity', 'Form 3 (Sensory Clue)',
      'A red circle on a pure white background — the simplest national flag in the world, representing the rising sun.',
      'Japan',
      ['Japan', 'South Korea', 'Bangladesh', 'Palau'],
      'Synonym Bridge',
      'Japan\'s flag is the Hinomaru — "circle of the sun." South Korea has a yin-yang and trigrams. Bangladesh has a red circle slightly off-center on green. Palau has a yellow circle on blue.',
      100, 'easy', 'Red circle'),
    q('The Oddity', 'Form 3 (Sensory Clue)',
      'A white Nordic cross on a red background — the oldest continuously used national flag in the world, dating back to the 14th century.',
      'Denmark',
      ['Denmark', 'Norway', 'Sweden', 'Finland'],
      'Synonym Bridge',
      'The Dannebrog of Denmark has been used since 1370. Norway\'s flag has a blue cross outlined in white. Sweden\'s cross is yellow. Finland\'s cross is blue.',
      100, 'easy', 'Oldest flag'),
    q('The Oddity', 'Form 3 (Sensory Clue)',
      'Vertical bands of blue, white, and red — this tricolor pattern inspired dozens of other national flags after the revolution that birthed it.',
      'France',
      ['France', 'Netherlands', 'Russia', 'Luxembourg'],
      'Synonym Bridge',
      'France\'s Tricolore uses vertical blue-white-red. The Netherlands uses horizontal red-white-blue. Russia uses horizontal white-blue-red. Luxembourg uses horizontal red-white-light blue.',
      100, 'easy', 'Tricolor'),
    q('The Oddity', 'Form 3 (Sensory Clue)',
      'A green field with a yellow diamond containing a blue globe with 27 stars and a white banner reading "Ordem e Progresso" — the only flag with a star map of the night sky.',
      'Brazil',
      ['Brazil', 'Argentina', 'Mexico', 'Chile'],
      'Synonym Bridge',
      'Brazil\'s flag features the southern hemisphere star map as seen from Rio on Nov 15, 1889. Argentina has the Sun of May. Mexico has an eagle on a cactus. Chile has a single star.',
      100, 'easy', 'Star map'),
    q('The Oddity', 'Form 3 (Sensory Clue)',
      'A red maple leaf centered on a white square between two red vertical bands — one of the most recognizable flags in the world, adopted in 1965.',
      'Canada',
      ['Canada', 'Peru', 'Switzerland', 'Lebanon'],
      'Synonym Bridge',
      'Canada\'s 11-pointed maple leaf flag was adopted in 1965. Peru has vertical red-white-red with a coat of arms. Switzerland has a white cross on a red square. Lebanon has a cedar tree.',
      100, 'easy', 'Maple leaf'),
    q('The Oddity', 'Form 3 (Sensory Clue)',
      'A crimson field with a white crescent moon and five stars forming a pentagon shape — the moon represents a young nation rising.',
      'Singapore',
      ['Singapore', 'Malaysia', 'Turkey', 'Pakistan'],
      'Synonym Bridge',
      'Singapore\'s crescent and five stars represent democracy, peace, progress, justice, and equality. Malaysia has 14 stripes and a crescent with a 14-point star. Turkey has a crescent and single star.',
      100, 'easy', 'Crescent pentagon'),
    q('The Oddity', 'Form 3 (Sensory Clue)',
      'Three horizontal bands of saffron, white, and green, with a navy blue 24-spoke wheel (Ashoka Chakra) in the center of the white band.',
      'India',
      ['India', 'Niger', 'Ireland', 'Ivory Coast'],
      'Synonym Bridge',
      'India\'s Ashoka Chakra with 24 spokes is unique. Niger has an orange circle in the center. Ireland uses green-white-orange. Ivory Coast uses orange-white-green.',
      100, 'easy', '24-spoke wheel'),
    q('The Oddity', 'Form 3 (Sensory Clue)',
      'A Union Jack in the upper left corner on a blue field with six white stars — the stars represent the Southern Cross constellation.',
      'Australia',
      ['Australia', 'New Zealand', 'Fiji', 'Tuvalu'],
      'Synonym Bridge',
      'Australia\'s flag has six white stars (five for the Southern Cross, one Federation Star with seven points). New Zealand has four red stars with white borders.',
      100, 'easy', 'Southern Cross'),
    q('The Oddity', 'Form 3 (Sensory Clue)',
      'A plain green field with nothing else — the only national flag in the world that is a single solid color with no symbols, emblems, or designs.',
      'Libya',
      ['Libya', 'Saudi Arabia', 'Mauritania', 'Bangladesh'],
      'Synonym Bridge',
      'Libya\'s flag under Gaddafi (1977-2011) was solid green — the only mono-color flag in history. Since 2011 it has the tricolor with crescent and star. Saudi Arabia has Arabic script.',
      100, 'easy', 'Plain green'),
    q('The Oddity', 'Form 3 (Sensory Clue)',
      'A white cross on a red square — one of only two square national flags in the world, alongside the flag of a religious authority.',
      'Switzerland',
      ['Switzerland', 'Vatican City', 'Denmark', 'Austria'],
      'Synonym Bridge',
      'Switzerland and Vatican City are the only nations with square flags. Denmark\'s flag is rectangular with a Nordic cross. Austria\'s flag has three horizontal stripes.',
      100, 'easy', 'Square flag'),

    // ── Medium (11-20): 300 pts ──
    q('The Oddity', 'Form 3 (Sensory Clue)',
      'A black, red, and green tricolor with a Maasai shield and two crossed spears in the center — the shield represents the defense of freedom.',
      'Kenya',
      ['Kenya', 'Tanzania', 'Uganda', 'Malawi'],
      'Synonym Bridge',
      'Kenya\'s flag uniquely features a Maasai shield and spears. Tanzania has a diagonal black band with yellow borders. Uganda has a grey crowned crane. Malawi has a rising sun.',
      300, 'medium', 'Shield and spears'),
    q('The Oddity', 'Form 3 (Sensory Clue)',
      'A yellow, blue, and red horizontal tricolor with eight white stars in an arc on the blue band — the stars represent the eight provinces that declared independence.',
      'Venezuela',
      ['Venezuela', 'Colombia', 'Ecuador', 'Bolivia'],
      'Synonym Bridge',
      'Venezuela\'s flag has eight stars (originally seven, eighth added in 2006 for Guayana). Colombia has yellow-blue-red but no stars. Ecuador has a coat of arms.',
      300, 'medium', 'Eight stars arc'),
    q('The Oddity', 'Form 3 (Sensory Clue)',
      'A horizontal bicolor of white over red with the coat of arms featuring a crowned white eagle — the flag\'s colors are reversed from the more common red-over-white pattern.',
      'Poland',
      ['Poland', 'Indonesia', 'Monaco', 'Austria'],
      'Synonym Bridge',
      'Poland\'s flag is white over red with an eagle on the state version. Indonesia is red over white. Monaco is red over white. Austria has three horizontal bands.',
      300, 'medium', 'White over red'),
    q('The Oddity', 'Form 3 (Sensory Clue)',
      'A blue field with a golden map of the country and two olive branches — the only national flag that depicts the country\'s own territorial outline.',
      'Cyprus',
      ['Cyprus', 'Kosovo', 'Antarctica', 'Lebanon'],
      'Synonym Bridge',
      'Cyprus is the only UN member whose flag shows its own map. Kosovo (partially recognized) also has a map. Antarctica is not a country.',
      300, 'medium', 'Map flag'),
    q('The Oddity', 'Form 3 (Sensory Clue)',
      'A red field with a black two-headed eagle — one of the most ancient flag symbols in the world, dating back to the Byzantine Empire.',
      'Albania',
      ['Albania', 'Serbia', 'Montenegro', 'Greece'],
      'Synonym Bridge',
      'Albania\'s two-headed eagle (flamur) derives from the Byzantine symbol used by Skanderbeg. Serbia has a white two-headed eagle with a shield. Montenegro has a golden two-headed eagle.',
      300, 'medium', 'Two-headed eagle'),
    q('The Oddity', 'Form 3 (Sensory Clue)',
      'Two overlapping triangles forming a six-pointed star shape — the only national flag that is not a rectangle or square.',
      'Nepal',
      ['Nepal', 'Bhutan', 'Switzerland', 'Maldives'],
      'Synonym Bridge',
      'Nepal\'s flag is the only non-quadrilateral national flag — two stacked pennants. Bhutan has a dragon. Switzerland is a square. Maldives is a rectangle with a crescent.',
      300, 'medium', 'Non-rectangular'),
    q('The Oddity', 'Form 3 (Sensory Clue)',
      'A red field with a yellow star in the center — one of the few remaining national flags featuring a communist star, unchanged since 1955.',
      'Vietnam',
      ['Vietnam', 'China', 'North Korea', 'Laos'],
      'Synonym Bridge',
      'Vietnam\'s gold star on red field has been in use since 1945. China has five stars. North Korea has a star in a circle. Laos has a three-headed elephant.',
      300, 'medium', 'Gold star'),
    q('The Oddity', 'Form 3 (Sensory Clue)',
      'A horizontal tricolor of blue, black, and white — the colors represent the sky, the soil, and the snow and symbolize the country\'s geography.',
      'Estonia',
      ['Estonia', 'Latvia', 'Lithuania', 'Finland'],
      'Synonym Bridge',
      'Estonia\'s blue-black-white tricolor is unique. Latvia is maroon-white-maroon. Lithuania is yellow-green-red. Finland is white with a blue Nordic cross.',
      300, 'medium', 'Blue-black-white'),
    q('The Oddity', 'Form 3 (Sensory Clue)',
      'A dark blue field with the golden silhouette of a stepped temple — the only national flag with a building as its central emblem.',
      'Cambodia',
      ['Cambodia', 'Myanmar', 'Thailand', 'Laos'],
      'Synonym Bridge',
      'Cambodia\'s flag features Angkor Wat in white/black silhouette (depending on the version). No other national flag has a building as its main symbol.',
      300, 'medium', 'Angkor Wat'),
    q('The Oddity', 'Form 3 (Sensory Clue)',
      'A light blue field with a yellow sun in the center, crossed by an eagle and holding a traditional shanyrak — the crown of a yurt.',
      'Kyrgyzstan',
      ['Kyrgyzstan', 'Kazakhstan', 'Tajikistan', 'Mongolia'],
      'Synonym Bridge',
      'Kyrgyzstan\'s flag features a 40-ray sun with a tunduk (yurt crown). Kazakhstan has a golden eagle under a sun. Tajikistan has a crown and stars. Mongolia has the Soyombo symbol.',
      300, 'medium', 'Yurt crown'),

    // ── Challenging (21-25): 400 pts ──
    q('The Oddity', 'Form 3 (Sensory Clue)',
      'Five horizontal bands of blue, white, red, white, and blue with a green triangle on the hoist side — the green triangle represents agriculture and the stars of the Southern Cross.',
      'Solomon Islands',
      ['Solomon Islands', 'Fiji', 'Vanuatu', 'Papua New Guinea'],
      'Synonym Bridge',
      'The Solomon Islands flag has diagonal yellow stripe on green triangle with five stars. Fiji has a Union Jack. Vanuatu has a yellow Y-shape. PNG has a bird of paradise.',
      400, 'challenging', 'Five stars'),
    q('The Oddity', 'Form 3 (Sensory Clue)',
      'A horizontal tricolor of green, white, and red with the emblem of a lion holding a sword in front of a rising sun — almost identical to a Middle Eastern flag except for the script.',
      'Iran',
      ['Iran', 'Iraq', 'Syria', 'Yemen'],
      'Synonym Bridge',
      'Iran\'s flag has the lion and sun emblem (or the Allah emblem post-1979) with "Allahu Akbar" repeated 22 times. Tajikistan has similar colors but with a crown.',
      400, 'challenging', 'Lion and sun'),
    q('The Oddity', 'Form 3 (Sensory Clue)',
      'Three vertical bands of green, gold, and red with a six-pointed star in the center — the green represents hope, gold represents peace, and red represents the blood of martyrs.',
      'Suriname',
      ['Suriname', 'Senegal', 'Guinea', 'Mali'],
      'Synonym Bridge',
      'Suriname is the only South American country with green-gold-red vertical bands and a central star. Senegal uses the same colors but horizontal with a green star.',
      400, 'challenging', 'Green-gold-red'),
    q('The Oddity', 'Form 3 (Sensory Clue)',
      'A horizontal bicolor of blue and yellow with a black triangle on the hoist side — the "V" shape formed by the yellow represents the country pointing towards a golden future.',
      'Saint Lucia',
      ['Saint Lucia', 'Bahamas', 'Barbados', 'Grenada'],
      'Synonym Bridge',
      'Saint Lucia\'s flag has a black and white triangle on blue with a yellow triangle. Barbados has a trident. Bahamas has a black triangle with aquamarine and yellow.',
      400, 'challenging', 'Triangle V'),
    q('The Oddity', 'Form 3 (Sensory Clue)',
      'A green field with a white-bordered red triangle on the hoist and a golden bird of paradise in flight — the bird represents the country\'s emergence as a nation.',
      'Papua New Guinea',
      ['Papua New Guinea', 'Solomon Islands', 'Fiji', 'Vanuatu'],
      'Synonym Bridge',
      'PNG\'s flag features the Raggiana bird of paradise in gold. Solomon Islands has a yellow diagonal stripe with stars. Fiji has a Union Jack. Vanuatu has a boar\'s tusk.',
      400, 'challenging', 'Bird of paradise'),

    // ── Expert (26-30): 500 pts ──
    q('The Oddity', 'Form 3 (Sensory Clue)',
      'A blue field with a yellow diagonal stripe bordered by white stripes — the diagonal represents the equator passing through the country\'s territorial waters.',
      'Nauru',
      ['Nauru', 'Kiribati', 'Tuvalu', 'Marshall Islands'],
      'Synonym Bridge',
      'Nauru\'s flag has a 12-pointed star on a blue field with a yellow horizontal stripe just below the equator. Kiribati has a frigate bird and sun, Tuvalu has the Union Jack.',
      500, 'expert', 'Equator stripe'),
    q('The Oddity', 'Form 3 (Sensory Clue)',
      'A red field with a black and white traditional emblem in the center — the emblem is the Soyombo, a geometric abstraction representing fire, sun, moon, earth, water, and the yin-yang.',
      'Mongolia',
      ['Mongolia', 'Kyrgyzstan', 'Bhutan', 'Nepal'],
      'Synonym Bridge',
      'Mongolia\'s Soyombo symbol on the left hoist includes fire, sun, moon, triangles, and yin-yang. Kyrgyzstan has a tunduk (yurt crown). Bhutan has a dragon. Nepal has two pennants.',
      500, 'expert', 'Soyombo'),
    q('The Oddity', 'Form 3 (Sensory Clue)',
      'A blue-white-blue horizontal triband with five blue stars arranged in an "X" pattern on the white stripe — representing the five stars of the Southern Cross as seen from the country.',
      'Honduras',
      ['Honduras', 'Guatemala', 'Nicaragua', 'El Salvador'],
      'Synonym Bridge',
      'Honduras\'s flag has five blue stars representing the Central American Federation. Actually, this description also fits, but the "X" pattern is uniquely Honduran.',
      500, 'expert', 'X-pattern stars'),
    q('The Oddity', 'Form 3 (Sensory Clue)',
      'A light blue field with 24 golden rays emanating from the sun and a condor shield with three volcanoes — one of the oldest flags in South America.',
      'Ecuador',
      ['Ecuador', 'Colombia', 'Venezuela', 'Peru'],
      'Synonym Bridge',
      'Ecuador\'s flag features the condor on a shield with Chimborazo volcano. Colombia\'s tricolor has no coat of arms on the civil flag. Venezuela has stars.',
      500, 'expert', 'Condor shield'),
    q('The Oddity', 'Form 3 (Sensory Clue)',
      'A horizontal tricolor of black, red, and green with a white emblem of a hoe crossed with an AK-47 over an open book — the only national flag that includes an automatic weapon.',
      'Mozambique',
      ['Mozambique', 'Angola', 'Zimbabwe', 'Guinea-Bissau'],
      'Synonym Bridge',
      'Mozambique\'s flag is the only one with a modern firearm (AK-47). Angola has a machete and cogwheel. Zimbabwe has the Zimbabwe bird. Guinea-Bissau has a black star.',
      500, 'expert', 'AK-47'),
  ],
  ['Grid', 'Flags of the World: Decoding National Symbols', 'Theme:Geography', 'Human', 'Visual', 'Classic', 'Mode:Focused', 'AI:Suggested'],
);

// ═══════════════════════════════════════════════════════════════════
// TOPIC 3: Geographic Superlatives (Lens: Numbers & Scale)
// ═══════════════════════════════════════════════════════════════════

const topic3 = cat(
  'Geographic Superlatives: The Extremes of Planet Earth',
  'Geography',
  'From the deepest ocean trench to the highest peak, explore Earth\'s most extreme geographic features.',
  'focused',
  'Numbers & Scale',
  [
    // ── Easy (1-10): 100 pts ──
    q('Numbers & Scale', 'Form 7 (The Question Lead)',
      'Which mountain stands 8,848.86 meters above sea level and was first summited by Edmund Hillary and Tenzing Norgay in 1953?',
      'Mount Everest',
      ['Mount Everest', 'K2', 'Kangchenjunga', 'Lhotse'],
      'Everyday Link',
      'Mount Everest was re-measured at 8,848.86 m in 2020. K2 is 8,611 m, Kangchenjunga is 8,586 m, and Lhotse is 8,516 m.',
      100, 'easy', 'Hillary'),
    q('Numbers & Scale', 'Form 7 (The Question Lead)',
      'At 11,034 meters deep, this is the deepest known point in Earth\'s oceans, located in the western Pacific Ocean.',
      'Challenger Deep',
      ['Challenger Deep', 'Tonga Trench', 'Puerto Rico Trench', 'Java Trench'],
      'Everyday Link',
      'Challenger Deep in the Mariana Trench is Earth\'s deepest point. The Tonga Trench is ~10,882 m, Puerto Rico ~8,400 m, Java Trench ~7,725 m.',
      100, 'easy', 'Deepest'),
    q('Numbers & Scale', 'Form 7 (The Question Lead)',
      'Spanning 6,650 kilometers, which African river is the longest in the world, flowing north through 11 countries before emptying into the Mediterranean Sea?',
      'Nile River',
      ['Nile River', 'Amazon River', 'Congo River', 'Niger River'],
      'Everyday Link',
      'The Nile at ~6,650 km edges out the Amazon (~6,400 km). Congo is ~4,700 km, Niger ~4,180 km.',
      100, 'easy', 'Longest river'),
    q('Numbers & Scale', 'Form 7 (The Question Lead)',
      'Which country spans 11 time zones and contains the coldest permanently inhabited settlement on Earth, Oymyakon, where temperatures drop below -50°C?',
      'Russia',
      ['Russia', 'Canada', 'China', 'United States'],
      'Everyday Link',
      'Russia spans 11 time zones across 17.1 million km². Oymyakon holds the record for coldest inhabited place. Canada spans 6 time zones.',
      100, 'easy', '11 time zones'),
    q('Numbers & Scale', 'Form 7 (The Question Lead)',
      'At 6,959 meters below sea level, which ocean\'s deepest point — the Milwaukee Deep in the Puerto Rico Trench — makes it the deepest point in this body of water?',
      'Atlantic Ocean',
      ['Atlantic Ocean', 'Pacific Ocean', 'Indian Ocean', 'Southern Ocean'],
      'Everyday Link',
      'The Atlantic\'s deepest point is 8,376 m at the Puerto Rico Trench. The Pacific has the deepest overall (Mariana Trench at 11,034 m).',
      100, 'easy', 'Milwaukee Deep'),
    q('Numbers & Scale', 'Form 7 (The Question Lead)',
      'At approximately 5.5 million square kilometers, this is the largest rainforest on Earth, producing 20% of the world\'s oxygen.',
      'Amazon Rainforest',
      ['Amazon Rainforest', 'Congo Basin', 'Southeast Asian Rainforest', 'Daintree Rainforest'],
      'Everyday Link',
      'The Amazon covers 5.5 million km² across nine South American countries. Congo Basin is ~3.7 million km². Daintree is ~1,200 km² in Australia.',
      100, 'easy', 'Largest rainforest'),
    q('Numbers & Scale', 'Form 7 (The Question Lead)',
      'Reaching 4,207 meters above sea level, this volcanic peak in Hawaii is the tallest mountain on Earth when measured from its base on the ocean floor.',
      'Mauna Kea',
      ['Mauna Kea', 'Mauna Loa', 'Mount Everest', 'Mount Kilimanjaro'],
      'Everyday Link',
      'Mauna Kea measures 10,211 m from seafloor base to summit. Everest is tallest above sea level (8,849 m). Mauna Loa is slightly shorter at ~9,170 m base-to-peak.',
      100, 'easy', 'Seafloor base'),
    q('Numbers & Scale', 'Form 7 (The Question Lead)',
      'At 1,642 meters deep, this Siberian lake contains 20% of the world\'s unfrozen surface freshwater — more than all the North American Great Lakes combined.',
      'Lake Baikal',
      ['Lake Baikal', 'Lake Tanganyika', 'Caspian Sea', 'Lake Superior'],
      'Everyday Link',
      'Lake Baikal is the deepest lake (1,642 m) and holds ~23,600 km³ of water. Tanganyika is 1,470 m deep. The Caspian Sea is saline. Superior has only 12,100 km³.',
      100, 'easy', '20% freshwater'),
    q('Numbers & Scale', 'Form 7 (The Question Lead)',
      'Reaching a surface temperature of 70.7°C, this Iranian desert is the hottest place on Earth by surface temperature, recorded by NASA satellites.',
      'Lut Desert',
      ['Lut Desert', 'Sahara Desert', 'Death Valley', 'Sonoran Desert'],
      'Everyday Link',
      'The Dasht-e Lut (Lut Desert) in Iran recorded 70.7°C (159°F) surface temp in 2005. Death Valley\'s air temp record is 56.7°C. Sahara\'s surface temp peaks around 55°C.',
      100, 'easy', 'Iran'),
    q('Numbers & Scale', 'Form 7 (The Question Lead)',
      'At 11,000 kilometers, this island country has the longest coastline in the world, with over 52,000 islands forming its archipelago.',
      'Canada',
      ['Canada', 'Norway', 'Indonesia', 'Australia'],
      'Everyday Link',
      'Canada has the world\'s longest coastline at 202,080 km including islands. Norway has ~103,000 km, Indonesia ~54,716 km, Australia ~25,760 km.',
      100, 'easy', 'Longest coastline'),

    // ── Medium (11-20): 300 pts ──
    q('Numbers & Scale', 'Form 7 (The Question Lead)',
      'At approximately 30.37 million square kilometers, which continent is the second-largest by land area, with over 10% of Earth\'s total land surface?',
      'Africa',
      ['Africa', 'North America', 'South America', 'Antarctica'],
      'Everyday Link',
      'Africa is ~30.37 million km² (second-largest). Asia is largest at ~44.6 million km². North America ~24.7 million, South America ~17.8 million.',
      300, 'medium', '10.5 mil'),
    q('Numbers & Scale', 'Form 7 (The Question Lead)',
      'Stretching 2,900 kilometers, this is the world\'s largest coral reef system, visible from outer space and comprising over 2,900 individual reefs.',
      'Great Barrier Reef',
      ['Great Barrier Reef', 'Mesoamerican Reef', 'New Caledonia Barrier Reef', 'Red Sea Coral Reef'],
      'Everyday Link',
      'The Great Barrier Reef spans 2,300+ km off Australia. Mesoamerican is ~1,000 km. New Caledonia is ~1,500 km. Red Sea has ~2,000 km of fringing reefs.',
      300, 'medium', 'Australia reef'),
    q('Numbers & Scale', 'Form 7 (The Question Lead)',
      'At -430 meters below sea level, this Middle Eastern body of water has shores that represent the lowest land-based elevation on Earth.',
      'Dead Sea',
      ['Dead Sea', 'Sea of Galilee', 'Caspian Sea', 'Lake Assal'],
      'Everyday Link',
      'The Dead Sea\'s shores are at -430 m (and dropping 1 m/year). Lake Assal in Djibouti is -155 m. The Caspian Sea is -28 m.',
      300, 'medium', 'Lowest elevation'),
    q('Numbers & Scale', 'Form 7 (The Question Lead)',
      'At 2,500 kilometers per hour, which planet in our solar system has the fastest wind speeds ever recorded, exceeding the speed of sound?',
      'Neptune',
      ['Neptune', 'Jupiter', 'Saturn', 'Uranus'],
      'Everyday Link',
      'Neptune has winds up to 2,100 km/h — supersonic speeds. Jupiter\'s Great Red Spot winds reach ~650 km/h. Saturn\'s jet streams reach ~1,800 km/h.',
      300, 'medium', 'Neptune winds'),
    q('Numbers & Scale', 'Form 7 (The Question Lead)',
      'With an area of 371,000 square kilometers, this is the largest lake on Earth by surface area — often mistaken for a sea because of its saline waters.',
      'Caspian Sea',
      ['Caspian Sea', 'Lake Superior', 'Lake Victoria', 'Aral Sea'],
      'Everyday Link',
      'The Caspian Sea is 371,000 km² — technically a lake. Lake Superior is 82,100 km². Lake Victoria is 68,800 km². The Aral Sea has shrunk dramatically.',
      300, 'medium', 'Largest lake'),
    q('Numbers & Scale', 'Form 7 (The Question Lead)',
      'Receiving 11,871 millimeters of rain annually, this village in India holds the Guinness World Record for the highest average annual rainfall.',
      'Mawsynram',
      ['Mawsynram', 'Cherrapunji', 'Mount Waialeale', 'Tutunendo'],
      'Everyday Link',
      'Mawsynram, Meghalaya receives ~11,871 mm/year. Cherrapunji (nearby) averages ~11,777 mm. Mount Waialeale (Hawaii) gets ~9,500 mm. Tutunendo (Colombia) ~11,770 mm.',
      300, 'medium', 'Rainfall record'),
    q('Numbers & Scale', 'Form 7 (The Question Lead)',
      'At 3,212 meters per second, a tsunami in this bay created the highest wave ever recorded, triggered by a massive earthquake and landslide.',
      'Lituya Bay',
      ['Lituya Bay', 'Fjord of Ísafjörður', 'Bay of Fundy', 'Hangzhou Bay'],
      'Everyday Link',
      'Lituya Bay, Alaska had a 524 m (1,720 ft) megatsunami in 1958. Bay of Fundy has the highest tides (~16 m). No other bay has recorded a tsunami wave this high.',
      300, 'medium', 'Megatsunami'),
    q('Numbers & Scale', 'Form 7 (The Question Lead)',
      'At 7,310 kilometers, which barrier reef is the world\'s second-longest, stretching from Mexico\'s Yucatán Peninsula to Honduras?',
      'Mesoamerican Barrier Reef',
      ['Mesoamerican Barrier Reef', 'Great Barrier Reef', 'Florida Reef', 'Red Sea Reef'],
      'Everyday Link',
      'The Mesoamerican Barrier Reef System is 1,000 km long. The Great Barrier Reef is the longest. Florida Reef is ~270 km. Red Sea reefs are fringing, not a single system.',
      300, 'medium', 'Second-longest reef'),
    q('Numbers & Scale', 'Form 7 (The Question Lead)',
      'With a salinity of 33.7%, this African body of water is the saltiest lake outside Antarctica — nearly 10 times saltier than the ocean.',
      'Lake Assal',
      ['Lake Assal', 'Dead Sea', 'Great Salt Lake', 'Lake Van'],
      'Everyday Link',
      'Lake Assal in Djibouti has 34.8% salinity. The Dead Sea is ~34%. Don Juan Pond in Antarctica is >40%. Great Salt Lake is ~27%.',
      300, 'medium', 'Salinity record'),
    q('Numbers & Scale', 'Form 7 (The Question Lead)',
      'At 680 meters, this waterfall on the border of Venezuela and Brazil is the tallest uninterrupted waterfall in the world.',
      'Angel Falls',
      ['Angel Falls', 'Tugela Falls', 'Yosemite Falls', 'Victoria Falls'],
      'Everyday Link',
      'Angel Falls (Kerepakupai Merú) drops 979 m total, 807 m uninterrupted. Tugela Falls drops 948 m. Yosemite is 739 m. Victoria Falls is only 108 m tall but 1,708 m wide.',
      300, 'medium', 'Tallest waterfall'),

    // ── Challenging (21-25): 400 pts ──
    q('Numbers & Scale', 'Form 7 (The Question Lead)',
      'At 86 meters below sea level and 56.7°C, this desert basin holds the record for the highest reliably recorded air temperature on Earth.',
      'Death Valley',
      ['Death Valley', 'Sahara Desert', 'Lut Desert', 'Danakil Depression'],
      'Everyday Link',
      'Death Valley\'s Furnace Creek recorded 56.7°C (134°F) in 1913. The Lut Desert has higher surface temperatures but not air temperature records. Danakil is hotter annually but not by single-day record.',
      400, 'challenging', 'Furnace Creek'),
    q('Numbers & Scale', 'Form 7 (The Question Lead)',
      'With an average width of 1,600 kilometers and a maximum depth of 4,400 meters, this mountain range is the longest continental mountain range on Earth.',
      'Andes',
      ['Andes', 'Rocky Mountains', 'Himalayas', 'Great Dividing Range'],
      'Everyday Link',
      'The Andes stretch 7,000 km along South America — the longest continental range. The Rockies are ~4,800 km. The Himalayas ~2,400 km. Great Dividing Range ~3,500 km.',
      400, 'challenging', 'Longest mountain range'),
    q('Numbers & Scale', 'Form 7 (The Question Lead)',
      'At 7.7 on the Volcanic Explosivity Index, which 1815 eruption was the largest in recorded history, causing the "Year Without a Summer" in 1816?',
      'Mount Tambora',
      ['Mount Tambora', 'Krakatoa', 'Mount Pinatubo', 'Vesuvius'],
      'Everyday Link',
      'Tambora (1815) was VEI-7, killing 71,000 people directly and ~200,000 from famine. Krakatoa (1883) was VEI-6. Pinatubo (1991) was VEI-6. Vesuvius (79 AD) was VEI-5.',
      400, 'challenging', '1815 eruption'),
    q('Numbers & Scale', 'Form 7 (The Question Lead)',
      'At 5.4 million square kilometers, this desert is the largest hot desert on Earth, nearly the size of China, though only 25% is covered in sand.',
      'Sahara',
      ['Sahara', 'Arabian Desert', 'Gobi Desert', 'Kalahari Desert'],
      'Everyday Link',
      'The Sahara is 9.2 million km² — the largest hot desert. The Arabian is 2.3 million km². Gobi is 1.3 million km². Kalahari is 900,000 km².',
      400, 'challenging', 'Largest hot desert'),
    q('Numbers & Scale', 'Form 7 (The Question Lead)',
      'With a diameter of 390 kilometers and a depth of 2,550 meters, which impact crater in South Africa is the largest confirmed impact structure on Earth?',
      'Vredefort Crater',
      ['Vredefort Crater', 'Chicxulub Crater', 'Sudbury Basin', 'Popigai Crater'],
      'Everyday Link',
      'Vredefort in South Africa has a 300 km diameter — the largest confirmed impact crater. Chicxulub is ~180 km (dinosaur killer). Sudbury is ~250 km. Popigai is ~100 km.',
      400, 'challenging', 'Largest crater'),

    // ── Expert (26-30): 500 pts ──
    q('Numbers & Scale', 'Form 7 (The Question Lead)',
      'At 10 cubic kilometers per second during peak flow, which massive flood 15,000 years ago carved the Channeled Scablands of Washington State and was caused by the collapse of an ice dam holding back Glacial Lake Missoula?',
      'Missoula Floods',
      ['Missoula Floods', 'Bonneville Flood', 'Altai Flood', 'Zanclean Flood'],
      'Everyday Link',
      'The Missoula Floods had a peak discharge of ~10 km³/s — roughly 60 times the Amazon\'s flow. The Bonneville Flood was from Lake Bonneville. The Altai Flood was in Siberia. The Zanclean Flood refilled the Mediterranean.',
      500, 'expert', 'Ice dam collapse'),
    q('Numbers & Scale', 'Form 7 (The Question Lead)',
      'At approximately 4.28°C, which deep ocean current — the engine of the global thermohaline circulation — contains the densest water on Earth, formed by the freezing of seawater in the Weddell Sea?',
      'Antarctic Bottom Water',
      ['Antarctic Bottom Water', 'North Atlantic Deep Water', 'Mediterranean Outflow', 'Circumpolar Deep Water'],
      'Everyday Link',
      'Antarctic Bottom Water is the coldest (-0.8°C) and densest water mass, formed at the Weddell and Ross Seas. NADW is warmer. Mediterranean Outflow is salty but warm.',
      500, 'expert', 'Weddell Sea'),
    q('Numbers & Scale', 'Form 7 (The Question Lead)',
      'At approximately 0.63 km/s² surface gravity, which moon in our solar system has the lowest surface gravity of any planetary-mass object — you could jump 40 meters high there?',
      'Mimas',
      ['Mimas', 'Enceladus', 'Miranda', 'Proteus'],
      'Everyday Link',
      'Mimas (Saturn\'s moon) has surface gravity of 0.064 m/s². Enceladus has 0.113 m/s². Miranda (Uranus) has 0.079 m/s². Proteus (Neptune) is tiny but think of these small moons.',
      500, 'expert', 'Jump 40 meters'),
    q('Numbers & Scale', 'Form 7 (The Question Lead)',
      'At 11,000 km², this iceberg — B-15 — broke off from the Ross Ice Shelf in 2000 and was the largest recorded iceberg in history.',
      'Iceberg B-15',
      ['Iceberg B-15', 'Iceberg A-68', 'Iceberg C-19', 'Iceberg A-38'],
      'Everyday Link',
      'B-15 calved in March 2000 at 11,000 km² (not 2 million — it was ~295 km × 37 km = ~11,000 km²). A-68 at 5,800 km² was smaller. C-19 was ~5,500 km².',
      500, 'expert', 'B-15 iceberg'),
    q('Numbers & Scale', 'Form 7 (The Question Lead)',
      'At up to 120 million metric tons of dust transported annually, this ancient lakebed is the largest source of airborne dust on Earth, fertilizing the Amazon rainforest with phosphorus from its ancient lakebed.',
      'Bodélé Depression',
      ['Bodélé Depression', 'Sahara Desert', 'Gobi Desert', 'Namib Desert'],
      'Everyday Link',
      'The Bodélé Depression in Chad is the dustiest place on Earth, a former lakebed of Megachad. Its phosphorus-rich dust crosses the Atlantic to fertilize the Amazon.',
      500, 'expert', 'Amazon fertilizer'),
  ],
  ['Grid', 'Geographic Superlatives: The Extremes of Planet Earth', 'Theme:Geography', 'Human', 'Facts', 'Classic', 'Mode:Focused', 'AI:Suggested'],
);

// ═══════════════════════════════════════════════════════════════════
// TOPIC 4: Famous Landmarks (Lens: Behind the Scenes)
// ═══════════════════════════════════════════════════════════════════

const topic4 = cat(
  'Famous Landmarks: The Stories Behind the Icons',
  'Geography',
  'Uncover the hidden histories, engineering feats, and human dramas behind the world\'s most iconic monuments.',
  'focused',
  'Behind the Scenes',
  [
    // ── Easy (1-10): 100 pts ──
    q('Behind the Scenes', 'Form 4 (Active Quote)',
      '"I found Rome a city of bricks and left it a city of marble" — which emperor\'s boast is embodied by this amphitheater, completed in 80 AD and still standing as the largest ancient amphitheater ever built?',
      'Colosseum',
      ['Colosseum', 'Pantheon', 'Circus Maximus', 'Roman Forum'],
      'Pop Culture Hook',
      'The Colosseum (Flavian Amphitheatre) held 50,000-80,000 spectators. Augustus said the quote. The Pantheon is a temple, Circus Maximus was a chariot racing track.',
      100, 'easy', 'Gladiator'),
    q('Behind the Scenes', 'Form 4 (Active Quote)',
      '"Keep, ancient lands, your storied pomp!" — this Emma Lazarus poem is inscribed on the pedestal of which 93-meter copper statue, a gift from France in 1886?',
      'Statue of Liberty',
      ['Statue of Liberty', 'Christ the Redeemer', 'Eiffel Tower', 'Big Ben'],
      'Pop Culture Hook',
      '"The New Colossus" is on the Statue of Liberty\'s pedestal. Christ the Redeemer is in Rio. The Eiffel Tower was built by France, not gifted.',
      100, 'easy', 'Emma Lazarus'),
    q('Behind the Scenes', 'Form 4 (Active Quote)',
      '"An elephant is a horse designed by a committee" — which 324-meter iron lattice tower, initially hated by Parisian intellectuals and intended to be dismantled after 20 years, became the most-visited paid monument in the world?',
      'Eiffel Tower',
      ['Eiffel Tower', 'Tokyo Tower', 'Empire State Building', 'CN Tower'],
      'Pop Culture Hook',
      'Gustave Eiffel\'s tower was built for the 1889 World\'s Fair and was meant to be temporary. A petition by artists called it a "tragic street lamp."',
      100, 'easy', 'Temporary'),
    q('Behind the Scenes', 'Form 4 (Active Quote)',
      'Built by 20,000 workers over 20 years using 2.3 million stone blocks — each weighing 2.5 tons — which ancient wonder was originally covered in smooth white limestone that made it shine like a star?',
      'Great Pyramid of Giza',
      ['Great Pyramid of Giza', 'Hanging Gardens', 'Temple of Artemis', 'Colossus of Rhodes'],
      'Pop Culture Hook',
      'The Great Pyramid\'s original limestone casing was stripped for Cairo buildings. The other three are also Seven Wonders but not pyramids.',
      100, 'easy', 'Limestone casing'),
    q('Behind the Scenes', 'Form 4 (Active Quote)',
      'Which 72-meter white marble mausoleum took 22 years and 20,000 artisans to complete, and its four minarets tilt slightly outward to protect the main dome if they ever collapse?',
      'Taj Mahal',
      ['Taj Mahal', 'Hagia Sophia', 'Alhambra', 'Blue Mosque'],
      'Pop Culture Hook',
      'The Taj Mahal\'s minarets lean 2-3 degrees outward by design. Hagia Sophia is a former church/mosque in Istanbul. Alhambra is a palace in Spain.',
      100, 'easy', 'Outward minarets'),
    q('Behind the Scenes', 'Form 4 (Active Quote)',
      'Which 319-meter Art Deco skyscraper secretly added a 56-meter spire inside the building during construction, revealed only after the rival 40 Wall Street topped out \xe2\x80\x94 making it the world\'s tallest building in 1930?',
      'Chrysler Building',
      ['Chrysler Building', 'Empire State Building', 'One World Trade Center', 'Burj Khalifa'],
      'Pop Culture Hook',
      "William Van Alen secretly assembled the Chrysler Building\'s spire inside the building and hoisted it into place after 40 Wall Street was completed. The Empire State Building surpassed it 11 months later.",
      100, 'easy', 'Secret spire'),

    q('Behind the Scenes', 'Form 4 (Active Quote)',
      'Which ancient Incan citadel was never found by Spanish conquistadors, and was only brought to international attention in 1911 by a Yale historian guided by a local farmer\'s 11-year-old son?',
      'Machu Picchu',
      ['Machu Picchu', 'Chichen Itza', 'Nazca Lines', 'Ollantaytambo'],
      'Pop Culture Hook',
      'Hiram Bingham was led to Machu Picchu by Pablito, the son of Melchor Arteaga. The Spanish never discovered it due to its remote mountain location.',
      100, 'easy', '1911 discovery'),
    q('Behind the Scenes', 'Form 4 (Active Quote)',
      'Which 828-meter tower holds seven Guinness World Records including tallest building, highest observation deck, and tallest elevator — and uses a high-pressure pumped concrete system specially developed because cranes couldn\'t reach the top?',
      'Burj Khalifa',
      ['Burj Khalifa', 'Shanghai Tower', 'Makkah Clock Royal Tower', 'Petronas Towers'],
      'Pop Culture Hook',
      'Burj Khalifa\'s concrete was pumped to 606 meters — a world record. The Shanghai Tower is 632 m. Petronas are 452 m.',
      100, 'easy', 'Pumped concrete'),
    q('Behind the Scenes', 'Form 4 (Active Quote)',
      'Which 5-kilometer-long defensive wall built from the 3rd century BC to the 17th century was NOT actually visible from space — contrary to the popular myth?',
      'Great Wall of China',
      ['Great Wall of China', 'Hadrian\'s Wall', 'Berlin Wall', 'Walls of Constantinople'],
      'Pop Culture Hook',
      'The Great Wall is not visible from space with the naked eye — it\'s too narrow. This myth was debunked by multiple astronauts including Yang Liwei.',
      100, 'easy', 'Space myth'),
    q('Behind the Scenes', 'Form 4 (Active Quote)',
      'Which massive sandstone formation in Australia\'s Northern Territory is sacred to the Anangu people and has two UNESCO listings — one for nature and one for culture?',
      'Uluru',
      ['Uluru', 'Wave Rock', 'Kata Tjuta', 'Bungle Bungles'],
      'Pop Culture Hook',
      'Uluru (Ayers Rock) is 348 m tall with most of its mass underground. Climbing was banned in 2019. Kata Tjuta (the Olgas) is nearby but is 36 domes, not a monolith.',
      100, 'easy', 'Two UNESCO'),

    // ── Medium (11-20): 300 pts ──
    q('Behind the Scenes', 'Form 4 (Active Quote)',
      '"I have not failed. I\'ve just found 10,000 ways that won\'t work" — which monument-carving project faced 14 years of legal battles, 9,000 workers, and the sculptor\'s death before completion — with his son finishing the work decades later?',
      'Mount Rushmore',
      ['Mount Rushmore', 'Crazy Horse Memorial', 'Stone Mountain', 'Valley of the Kings'],
      'Pop Culture Hook',
      'Gutzon Borglum died in 1941 before Rushmore was finished; his son Lincoln completed it. The Crazy Horse Memorial is also in South Dakota and is a similarly massive carving.',
      300, 'medium', 'Borglum'),
    q('Behind the Scenes', 'Form 4 (Active Quote)',
      'Which ancient city carved into rose-red cliffs was the capital of the Nabataean Kingdom, had a sophisticated water management system, and was lost to the Western world until a Swiss explorer disguised as a Bedouin rediscovered it in 1812?',
      'Petra',
      ['Petra', 'Palmyra', 'Babylon', 'Persepolis'],
      'Pop Culture Hook',
      'Johann Ludwig Burckhardt rediscovered Petra disguised as Sheikh Ibrahim. Palmyra is in Syria, Babylon in Iraq, Persepolis in Iran.',
      300, 'medium', 'Rediscovered 1812'),
    q('Behind the Scenes', 'Form 4 (Active Quote)',
      'Which 70,000-seat stadium was built in just 1,000 days using specially invented concrete that set underwater — and could be flooded to stage mock naval battles?',
      'Colosseum',
      ['Colosseum', 'Circus Maximus', 'Stadium of Domitian', 'Amphitheatre of Capua'],
      'Pop Culture Hook',
      'The Colosseum used Roman concrete (opus caementicium) and could be flooded for naumachiae. The Circus Maximus was for chariot racing, not naval battles.',
      300, 'medium', 'Naval battles'),
    q('Behind the Scenes', 'Form 4 (Active Quote)',
      'Which 6,500-kilometer-long trade route — not a single road but a network of paths — connected China to the Mediterranean for over 1,500 years, and was named by a German geographer in 1877?',
      'Silk Road',
      ['Silk Road', 'Amber Road', 'Incense Route', 'Spice Route'],
      'Pop Culture Hook',
      'Ferdinand von Richthofen coined "Seidenstraße" (Silk Road) in 1877. The Amber Road ran from the Baltic to the Mediterranean. The Incense Route was in Arabia.',
      300, 'medium', 'Richthofen'),
    q('Behind the Scenes', 'Form 4 (Active Quote)',
      'Which 1,700-year-old temple in Rome has the world\'s largest unreinforced concrete dome — a 43.3-meter span that architects still don\'t fully understand how the Romans achieved?',
      'Pantheon',
      ['Pantheon', 'Colosseum', 'Basilica of Maxentius', 'Baths of Caracalla'],
      'Pop Culture Hook',
      'The Pantheon\'s dome uses progressively lighter aggregate as it rises — travertine at the base, tufa in the middle, pumice at the top. The oculus is 8.2 m wide.',
      300, 'medium', '43.3m dome'),
    q('Behind the Scenes', 'Form 4 (Active Quote)',
      'Which 2,300-year-old lighthouse was one of the Seven Wonders and stood 100 meters tall on an island off Egypt — using mirrors to reflect sunlight by day and a furnace by night?',
      'Lighthouse of Alexandria',
      ['Lighthouse of Alexandria', 'Colossus of Rhodes', 'Temple of Artemis', 'Mausoleum at Halicarnassus'],
      'Pop Culture Hook',
      'The Pharos of Alexandria on Pharos Island used polished bronze mirrors. It was damaged by earthquakes between 956-1323 AD. The French word "phare" (lighthouse) comes from it.',
      300, 'medium', 'Pharos'),
    q('Behind the Scenes', 'Form 4 (Active Quote)',
      'Which 800-year-old Gothic cathedral survived the French Revolution, two world wars, and a devastating 2019 fire — and was built on the site of an ancient Roman temple to Jupiter?',
      'Notre-Dame de Paris',
      ['Notre-Dame de Paris', 'Sainte-Chapelle', 'Chartres Cathedral', 'Sacré-Cœur'],
      'Pop Culture Hook',
      'Notre-Dame\'s foundation contains Roman ruins. After the 2019 fire, it\'s being rebuilt using medieval techniques. Sainte-Chapelle is nearby but was built for Louis IX\'s relics.',
      300, 'medium', '2019 fire'),
    q('Behind the Scenes', 'Form 4 (Active Quote)',
      'Which ancient citadel in Athens was built under Pericles in the 5th century BC, survived being used as a church, a mosque, and an ammunition dump — the latter causing it to explode in 1687?',
      'Parthenon',
      ['Parthenon', 'Erechtheion', 'Temple of Hephaestus', 'Temple of Olympian Zeus'],
      'Pop Culture Hook',
      'The Parthenon was blown up when Venetian mortar hit Ottoman gunpowder stored inside. It was a temple to Athena, then a church, then a mosque.',
      300, 'medium', '1687 explosion'),
    q('Behind the Scenes', 'Form 4 (Active Quote)',
      'Which massive 73-meter waterfall on the Zambia-Zimbabwe border is locally called "Mosi-oa-Tunya" — "the smoke that thunders" — and is one of the Seven Natural Wonders?',
      'Victoria Falls',
      ['Victoria Falls', 'Niagara Falls', 'Iguazu Falls', 'Angel Falls'],
      'Pop Culture Hook',
      'David Livingstone named it after Queen Victoria in 1855. Mosi-oa-Tunya creates a spray visible from 50 km away. Niagara is shorter at 51 m.',
      300, 'medium', 'Smoke that thunders'),
    q('Behind the Scenes', 'Form 4 (Active Quote)',
      'Which 2,000-year-old Roman aqueduct in France carried 200 million liters of water daily across 50 kilometers — with a gradient of just 34 centimeters per kilometer?',
      'Pont du Gard',
      ['Pont du Gard', 'Aqua Claudia', 'Segovia Aqueduct', 'Aqua Appia'],
      'Pop Culture Hook',
      'The Pont du Gard has a gradient of only 1:3,000 (34 cm/km). The Aqua Claudia is in Rome. Segovia\'s aqueduct is in Spain.',
      300, 'medium', 'Gradient'),

    // ── Challenging (21-25): 400 pts ──
    q('Behind the Scenes', 'Form 4 (Active Quote)',
      '"A riddle, wrapped in a mystery, inside an enigma" — which 5,000-year-old prehistoric monument in England required stones weighing up to 25 tons to be transported from 240 kilometers away using methods still debated by archaeologists?',
      'Stonehenge',
      ['Stonehenge', 'Avebury', 'Carnac Stones', 'Ring of Brodgar'],
      'Pop Culture Hook',
      'Stonehenge\'s bluestones came from the Preseli Hills in Wales, 240 km away. Avebury is nearby but larger. Carnac is in Brittany. The Ring of Brodgar is in Orkney.',
      400, 'challenging', 'Preseli Hills'),
    q('Behind the Scenes', 'Form 4 (Active Quote)',
      'Which 12th-century temple complex in Cambodia was originally Hindu (dedicated to Vishnu), then Buddhist, and features a 3-kilometer bas-relief depicting Hindu epics and historical battles?',
      'Angkor Wat',
      ['Angkor Wat', 'Bayon Temple', 'Ta Prohm', 'Banteay Srei'],
      'Pop Culture Hook',
      'Angkor Wat was built by Suryavarman II for Vishnu, then converted to Buddhism under Jayavarman VII. It\'s the largest religious monument in the world at 162.6 hectares.',
      400, 'challenging', 'Vishnu to Buddha'),
    q('Behind the Scenes', 'Form 4 (Active Quote)',
      'Which underground city in Turkey descends 18 stories (85 meters) and could house 20,000 people with ventilation shafts, stables, churches, and rolling stone doors to seal off sections?',
      'Derinkuyu',
      ['Derinkuyu', 'Kaymakli', 'Özkonak', 'Mazı'],
      'Pop Culture Hook',
      'Derinkuyu is the deepest excavated underground city in Cappadocia, rediscovered in 1963 when a man found a room behind his wall during renovations.',
      400, 'challenging', 'Underground city'),
    q('Behind the Scenes', 'Form 4 (Active Quote)',
      'Which 1,500-year-old Buddhist temple carved into a 75-meter cliff face in China has a 71-meter seated Buddha — the world\'s largest — carved from the cliff itself?',
      'Leshan Giant Buddha',
      ['Leshan Giant Buddha', 'Bamiyan Buddhas', 'Tian Tan Buddha', 'Longmen Grottoes'],
      'Pop Culture Hook',
      'The Leshan Giant Buddha took 90 years to carve (713-803 AD). The Bamiyan Buddhas were destroyed by the Taliban in 2001. Tian Tan is on Lantau Island, Hong Kong.',
      400, 'challenging', '71-meter Buddha'),
    q('Behind the Scenes', 'Form 4 (Active Quote)',
      'Which 500-year-old stepwell in India descends 13 stories with 3,500 narrow steps in perfect geometric symmetry — an architectural wonder that also functioned as a community gathering space in the cool depths?',
      'Chand Baori',
      ['Chand Baori', 'Rani ki Vav', 'Adalaj Stepwell', 'Agrasen ki Baoli'],
      'Pop Culture Hook',
      'Chand Baori in Rajasthan has 13 floors and 3,500 steps. Rani ki Vav in Gujarat is UNESCO-listed and more ornate. Adalaj is also in Gujarat.',
      400, 'challenging', 'Stepwell'),

    // ── Expert (26-30): 500 pts ──
    q('Behind the Scenes', 'Form 4 (Active Quote)',
      'Which enigmatic 15th-century Inca site features H-shaped stone blocks weighing up to 360 tons, fitted so precisely that a razor blade cannot be inserted between them — with no known method of transport?',
      'Sacsayhuamán',
      ['Sacsayhuamán', 'Ollantaytambo', 'Machu Picchu', 'Pisac'],
      'Pop Culture Hook',
      'Sacsayhuamán\'s zigzag walls above Cusco use megaliths up to 360 tons. The precision is so great that not even a sheet of paper fits between stones.',
      500, 'expert', '360-ton blocks'),
    q('Behind the Scenes', 'Form 4 (Active Quote)',
      'Which 2,000-year-old Nabataean structure in Saudi Arabia features a freestanding facade carved from a single rock outcrop and was left unfinished — revealing the top-down construction technique of the Nabataeans?',
      'Al-Khazneh',
      ['Al-Khazneh', 'The Monastery (Ad Deir)', 'Qasr al-Bint', 'The Siq'],
      'Pop Culture Hook',
      'Al-Khazneh (The Treasury) in Petra was carved top-down from a single sandstone face. The unfinished chamber reveals the Nabataean construction sequence.',
      500, 'expert', 'Nabataean technique'),
    q('Behind the Scenes', 'Form 4 (Active Quote)',
      'Which 100-kilometer stone path off the coast of Ireland consists of 40,000 interlocking basalt columns formed by volcanic activity 60 million years ago — and inspired the name of a popular tourist attraction?',
      'Giant\'s Causeway',
      ['Giant\'s Causeway', 'Fingal\'s Cave', 'Cliffs of Moher', 'Skellig Michael'],
      'Pop Culture Hook',
      'The Giant\'s Causeway formed from rapidly cooling lava creating hexagonal columns. Legend says Finn McCool built it to fight a Scottish giant.',
      500, 'expert', 'Basalt columns'),
    q('Behind the Scenes', 'Form 4 (Active Quote)',
      'Which 900-year-old temple in Myanmar has 7 terraces representing the seven steps to enlightenment and holds 504 Buddha statues — and was damaged by a 2016 earthquake that exposed previously hidden murals?',
      'Ananda Temple',
      ['Ananda Temple', 'Shwedagon Pagoda', 'Bagan temples', 'Thatbyinnyu Temple'],
      'Pop Culture Hook',
      'Ananda Temple in Bagan is the best-preserved of the Bagan temples. The 2016 earthquake revealed hidden paintings in the temple interiors.',
      500, 'expert', 'Bagan earthquake'),
    q('Behind the Scenes', 'Form 4 (Active Quote)',
      'Which 6.3-kilometer-long artificial waterway carved through the Isthmus of Corinth connects the Aegean and Ionian Seas, and was first attempted by Emperor Nero in 67 AD but not completed until 1893?',
      'Corinth Canal',
      ['Corinth Canal', 'Suez Canal', 'Panama Canal', 'Kiel Canal'],
      'Pop Culture Hook',
      'The Corinth Canal cuts through the Isthmus of Corinth in Greece, saving ships a 700 km journey around the Peloponnese. Nero personally broke ground with a golden shovel in 67 AD.',
      500, 'expert', 'Artificial waterway'),
  ],
  ['Grid', 'Famous Landmarks: The Stories Behind the Icons', 'Theme:Geography', 'Human', 'Visual', 'Classic', 'Mode:Focused', 'AI:Suggested'],
);

// ═══════════════════════════════════════════════════════════════════
// TOPIC 5: World Currencies (Lens: Origin Story)
// ═══════════════════════════════════════════════════════════════════

const topic5 = cat(
  'World Currencies: What\'s in a Name?',
  'Geography',
  'Discover the fascinating etymology and history behind the world\'s currencies — from lions and crowns to weights and measures.',
  'focused',
  'Origin Story',
  [
    // ── Easy (1-10): 100 pts ──
    q('Origin Story', 'Form 6 (The Contradiction)',
      'Named after the Spanish word for "weight," this currency is used by eight countries including Mexico, Cuba, and Argentina — yet none of them are in Europe.',
      'Peso',
      ['Peso', 'Real', 'Sol', 'Dollar'],
      'Etymology / Name Logic',
      '"Peso" means weight in Spanish, originating from the weight of silver coins. The Real is from "royal," Sol from "sun," Dollar from the German "Thaler."',
      100, 'easy', 'Spanish weight'),
    q('Origin Story', 'Form 6 (The Contradiction)',
      'This currency derives its name from the Latin word for "pound" (libra), and its symbol £ is a stylized letter L — yet it is used by a country that uses neither Latin nor the metric system.',
      'Pound Sterling',
      ['Pound Sterling', 'Euro', 'Franc', 'Drachma'],
      'Etymology / Name Logic',
      '£ comes from "libra pondo" (pound weight). The UK uses imperial measurements. Euro derives from Europe. Franc means "frank/free." Drachma is from the Greek "handful."',
      100, 'easy', 'Libra pondo'),
    q('Origin Story', 'Form 6 (The Contradiction)',
      'Named after a large silver coin from a Bohemian valley, this currency is used by more than 20 countries including Canada, Australia, and Singapore — but NOT the European nation it was named after.',
      'Dollar',
      ['Dollar', 'Pound', 'Euro', 'Franc'],
      'Etymology / Name Logic',
      '"Dollar" comes from the German "Thaler," shortened from "Joachimsthaler" — a silver coin from the Joachimsthal valley in Bohemia (now Czech Republic).',
      100, 'easy', 'Bohemian valley'),
    q('Origin Story', 'Form 6 (The Contradiction)',
      'Named after the metal it was originally minted from — despite now being made of nickel and brass — this coin is worth 1/100th of a US dollar.',
      'Penny',
      ['Penny', 'Nickel', 'Dime', 'Quarter'],
      'Etymology / Name Logic',
      'Penny comes from Old English "pening" and was originally made of copper. The British penny was silver then copper. The US penny was pure copper until 1982.',
      100, 'easy', 'Copper'),
    q('Origin Story', 'Form 6 (The Contradiction)',
      'Derived from the Greek word for "grasp" or "handful" — six obols could fit in one hand — this was the currency of Greece until 2001.',
      'Drachma',
      ['Drachma', 'Dinar', 'Dirham', 'Denarius'],
      'Etymology / Name Logic',
      'Drachma means "a handful" in Greek. Dinar comes from the Roman "denarius." Dirham comes from the Greek "drachma." Denarius means "containing ten."',
      100, 'easy', 'Handful'),
    q('Origin Story', 'Form 6 (The Contradiction)',
      'Named after the French word for "crown," this currency was used by France for over 600 years before the euro — and its name comes from the royal crown stamped on medieval coins.',
      'Franc',
      ['Franc', 'Livre', 'Écu', 'Louis'],
      'Etymology / Name Logic',
      'Franc comes from "Francorum Rex" (King of the Franks) stamped on Jean le Bon\'s coins. Livre means "pound." Écu means "shield." Louis was named after kings.',
      100, 'easy', 'French crown'),
    q('Origin Story', 'Form 6 (The Contradiction)',
      'Derived from the Roman silver coin "denarius," this currency is used by countries including Jordan, Iraq, and Kuwait — with its name traveling through Arabic into a dozen Middle Eastern nations.',
      'Dinar',
      ['Dinar', 'Dirham', 'Rial', 'Lira'],
      'Etymology / Name Logic',
      'Dinar comes from the Roman denarius (worth 10 asses). Dirham comes from drachma. Rial/Riyal from the Spanish "real" (royal). Lira from the Latin "libra."',
      100, 'easy', 'Denarius'),
    q('Origin Story', 'Form 6 (The Contradiction)',
      'Named after the crown symbol on medieval coins, this word means "crown" — from the royal crown stamped on medieval coins — and is used by the Czech Republic from the national coat of arms.',
      'Koruna',
      ['Koruna', 'Zloty', 'Forint', 'Leu'],
      'Etymology / Name Logic',
      'Koruna means "crown" — from the crown on the coin, not a lion. Zloty means "golden" in Polish. Forint comes from Florence\'s "fiorino." Leu means "lion" in Romanian.',
      100, 'easy', 'Crown'),
    q('Origin Story', 'Form 6 (The Contradiction)',
      'Meaning "golden" in its native language, this currency\'s name reflects the gold ducats that were once minted — though modern coins are made of cupronickel.',
      'Zloty',
      ['Zloty', 'Forint', 'Ruble', 'Hryvnia'],
      'Etymology / Name Logic',
      'Polish "złoty" means "golden." Forint comes from Florence. Ruble means "chopped piece" of silver. Hryvnia means "mane" or "necklace" in Ukrainian.',
      100, 'easy', 'Polish gold'),
    q('Origin Story', 'Form 6 (The Contradiction)',
      'Named after the silver mines of a specific mountain range in Europe, this currency was once backed by silver but is now the world\'s primary reserve currency.',
      'Dollar',
      ['Dollar', 'Euro', 'Yen', 'Swiss Franc'],
      'Etymology / Name Logic',
      'The Thaler originated from silver mined in Joachimsthal (Ore Mountains, Bohemia). The US adopted "dollar" from the Spanish "peso de ocho" which was based on the thaler.',
      100, 'easy', 'Silver mines'),

    // ── Medium (11-20): 300 pts ──
    q('Origin Story', 'Form 6 (The Contradiction)',
      'Named after the Florentine coin "fiorino" — which featured a lily flower — this currency is used by Hungary today, despite being named after an Italian city-state.',
      'Forint',
      ['Forint', 'Leu', 'Lev', 'Kuna'],
      'Etymology / Name Logic',
      'The fiorino was a gold coin from Florence bearing the lily (fleur-de-lis). Forint derives from this via Italian influence. Leu/Lev means "lion." Kuna means "marten."',
      300, 'medium', 'Florence lily'),
    q('Origin Story', 'Form 6 (The Contradiction)',
      'Meaning "cut" or "chopped piece" in its native language, this currency originally referred to a specific weight of silver chopped from a larger bar — used by Russia for over 500 years.',
      'Ruble',
      ['Ruble', 'Kopek', 'Hryvnia', 'Tenge'],
      'Etymology / Name Logic',
      'Ruble comes from Russian "rubit" meaning "to chop." Kopek comes from "kopyo" (spear) — St. George on the coin. Hryvnia is a necklace. Tenge is a Turkic word.',
      300, 'medium', 'Chopped silver'),
    q('Origin Story', 'Form 6 (The Contradiction)',
      'Named after the marten pelts once used as currency in the region, this currency was adopted by Croatia in 1994 — but no one has paid with a marten pelt for centuries.',
      'Kuna',
      ['Kuna', 'Tolar', 'Marka', 'Lev'],
      'Etymology / Name Logic',
      'Kuna means "marten" — marten pelts were a medieval trade currency. The kuna was used 1994-2022 before Croatia adopted the euro.',
      300, 'medium', 'Marten pelt'),
    q('Origin Story', 'Form 6 (The Contradiction)',
      'Named after a unit of weight — approximately 3.2 grams — this Chinese currency literally means "round," alluding to the shape of the coin, not its material.',
      'Yuan',
      ['Yuan', 'Renminbi', 'Jiao', 'Won'],
      'Etymology / Name Logic',
      'Yuan means "round object/circle" referring to round coins. Renminbi is "people\'s currency." Jiao is 1/10 yuan. Won is the Korean cognate of yuan.',
      300, 'medium', 'Round coin'),
    q('Origin Story', 'Form 6 (The Contradiction)',
      'Named after the Latin word for "shield" — which appeared on medieval Italian coins — this currency name was used by Portugal before the euro and by several former Portuguese colonies.',
      'Escudo',
      ['Escudo', 'Real', 'Peso', 'Dobra'],
      'Etymology / Name Logic',
      'Escudo means "shield" — from the coat of arms on coins. Real means "royal." Peso means "weight." Dobra means "doubloon" in São Tomé.',
      300, 'medium', 'Latin shield'),
    q('Origin Story', 'Form 6 (The Contradiction)',
      'Named after the Sanskrit word for "stamped coin," this currency is used by India, Pakistan, Indonesia, and several other nations — its name traveled across the Indian Ocean trade routes.',
      'Rupee',
      ['Rupee', 'Rupiah', 'Taka', 'Ringgit'],
      'Etymology / Name Logic',
      'Rupee comes from Sanskrit "rupya" (wrought silver, stamped). Rupiah is Indonesian/Malay variant. Taka means "coin" in Bengali. Ringgit means "jagged" (Spanish dollar edge).',
      300, 'medium', 'Sanskrit rupya'),
    q('Origin Story', 'Form 6 (The Contradiction)',
      'Derived from the Dutch word for "lion" (leeuw), this currency gets its name from the lions depicted on medieval Dutch thalers — but is used by Romania and Moldova.',
      'Leu',
      ['Leu', 'Lev', 'Lek', 'Litas'],
      'Etymology / Name Logic',
      'Leu (plural: Lei) means "lion" — from the Dutch leeuwendaalder (lion thaler). Lev is the Bulgarian cognate. Lek means Alexander the Great. Litas is from Lithuania.',
      300, 'medium', 'Dutch lion'),
    q('Origin Story', 'Form 6 (The Contradiction)',
      'Named after the "jagged edge" of the Spanish silver dollar — which traders would clip around the rim — this currency is used by Malaysia today.',
      'Ringgit',
      ['Ringgit', 'Baht', 'Dong', 'Kyat'],
      'Etymology / Name Logic',
      'Ringgit means "jagged" in Malay, referring to the milled edge of Spanish dollars. Baht is a Thai weight unit. Dong means "copper" in Vietnamese. Kyat is Burmese.',
      300, 'medium', 'Jagged edge'),
    q('Origin Story', 'Form 6 (The Contradiction)',
      'Named after a silver coin minted in a specific German valley, this currency was adopted by Slovenia as its pre-euro currency — one of many European currencies with the same etymological root.',
      'Tolar',
      ['Tolar', 'Koruna', 'Lats', 'Kroon'],
      'Etymology / Name Logic',
      'Tolar comes from Joachimsthaler — same root as dollar. Koruna means "crown." Lats is unique to Latvia. Kroon means "crown" in Estonian.',
      300, 'medium', 'Joachimsthaler'),
    q('Origin Story', 'Form 6 (The Contradiction)',
      'Derived from the Greek word for "small" — this fractional unit is 1/100 of a dinar in Jordan, a strange choice of a name for something representing such a tiny value.',
      'Fils',
      ['Fils', 'Paisa', 'Kopek', 'Centime'],
      'Etymology / Name Logic',
      'Fils comes from the Greek "follis" (small coin). Paisa is from Sanskrit. Kopek is Russian. Centime is French, from "cent" meaning 100.',
      300, 'medium', 'Greek follis'),

    // ── Challenging (21-25): 400 pts ──
    q('Origin Story', 'Form 6 (The Contradiction)',
      'Named after the medieval African kingdom of Ghana — despite being used by the modern nation of Ghana, which is geographically unrelated to the ancient empire — this currency replaced the British West African pound in 1965.',
      'Cedi',
      ['Cedi', 'Dalasi', 'Naira', 'Leone'],
      'Etymology / Name Logic',
      'Cedi means "cowrie shell" in Akan — shells were used as currency. It replaced the pound at independence. Dalasi is Gambia, Naira is Nigeria, Leone is Sierra Leone.',
      400, 'challenging', 'Cowrie shell'),
    q('Origin Story', 'Form 6 (The Contradiction)',
      'Meaning "dawn" in the Nyanja language — symbolizing the new beginning at independence — this currency replaced the East African shilling in Zambia (1968) and Malawi (1971).',
      'Kwacha',
      ['Kwacha', 'Birr', 'Lilangeni', 'Pula'],
      'Etymology / Name Logic',
      'Kwacha means "dawn" in Nyanja — Zambia and Malawi both use it, named for independence. Birr is from "silver" in Amharic. Lilangeni is from "emalangeni" (the royal family). Pula means "rain" in Tswana.',
      400, 'challenging', 'Dawn'),
    q('Origin Story', 'Form 6 (The Contradiction)',
      'Named after the Arabic word for "weight" — specifically 4.25 grams of silver — this currency originated in the Umayyad Caliphate and is still used by Morocco and the UAE today, though no longer tethered to silver.',
      'Dirham',
      ['Dirham', 'Dinar', 'Rial', 'Riyal'],
      'Etymology / Name Logic',
      'Dirham comes from the Greek "drachma" via Arabic. It originally weighed 2.97 grams of silver. Dinar is from denarius. Rial/Riyal is from Spanish real.',
      400, 'challenging', 'Drachma via Arabic'),
    q('Origin Story', 'Form 6 (The Contradiction)',
      'Meaning "rain" in the local language — because rain is precious in the Kalahari — this currency name was chosen by public contest when the country gained independence in 1976, and the name appears as a watermark on all banknotes.',
      'Pula',
      ['Pula', 'Rand', 'Loti', 'Kwacha'],
      'Etymology / Name Logic',
      'Botswana\'s "pula" reflects the value of rain in the semi-arid country. Rand is South Africa\'s (from Witwatersrand gold ridge). Loti is Lesotho\'s currency.',
      400, 'challenging', 'Botswana rain'),
    q('Origin Story', 'Form 6 (The Contradiction)',
      'Named after the Latin word for "ten" — because it was originally worth 10 asses — this coin was the standard Roman silver coin for 450 years and gave its name to currencies across the Middle East.',
      'Denarius',
      ['Denarius', 'Sestertius', 'Aureus', 'Dupondius'],
      'Etymology / Name Logic',
      'Denarius = "containing ten" (10 asses), later revalued to 16 asses. It survived as dinar, dinero, denier, and the "d" in £sd. Sestertius = 2.5 asses. Aureus = gold.',
      400, 'challenging', 'Ten asses'),

    // ── Expert (26-30): 500 pts ──
    q('Origin Story', 'Form 6 (The Contradiction)',
      'Named after Antonio Jose de Sucre, the independence hero who fought alongside Simon Bolivar and became Bolivia\'s first president — this currency was used by Ecuador until 2000, when hyperinflation forced the country to adopt the US dollar.',
      'Sucre',
      ['Sucre', 'Bolívar', 'Inti', 'Austral'],
      'Etymology / Name Logic',
      'The sucre was named after Antonio José de Sucre (not Christ — the Italian groschen "grosso" had Christ). But the sucre was named for the independence hero. Bolívar is Venezuela\'s currency named after Simón Bolívar.',
      500, 'expert', 'Independence hero'),
    q('Origin Story', 'Form 6 (The Contradiction)',
      'Derived from the Latin "corona" meaning "crown" — from the royal crown stamped on coins — this currency was used by Iceland for over a century before the 2008 financial crisis nearly destroyed it.',
      'Króna',
      ['Króna', 'Ríkisdalur', 'Aurar', 'Eyrir'],
      'Etymology / Name Logic',
      'Króna means "crown" from Latin corona — not from cattle. The Old Norse "fé" (cattle/wealth) is related to the English "fee." Aurar/eyrir was 1/100 króna.',
      500, 'expert', 'Iceland crown'),
    q('Origin Story', 'Form 6 (The Contradiction)',
      'Named after the Georgian word for "silver" — this term literally described the metal content of early coins minted in the 5th century BC in the Kingdom of Colchis, making it one of the oldest continuously named currencies in the world.',
      'Tetri',
      ['Tetri', 'Maneti', 'Abazi', 'Pul'],
      'Etymology / Name Logic',
      'Georgian "tetri" means "silver/white" — the currency of Georgia. Maneti was the Soviet-era ruble translation. Abazi was 19th century. Pul is copper.',
      500, 'expert', 'Georgian white'),
    q('Origin Story', 'Form 6 (The Contradiction)',
      'Named after the Quechua word for the sun — this was the currency of the Inca Empire (minted as gold discs) and was revived as Peru\'s currency in 1991 after hyperinflation destroyed its predecessor.',
      'Sol',
      ['Sol', 'Inti', 'Real', 'Escudo'],
      'Etymology / Name Logic',
      'The Peruvian Sol replaced the Inti (also meaning "sun" in Quechua) at 1 million to 1 in 1991 after hyperinflation. The Inti had replaced the Sol in 1985.',
      500, 'expert', 'Inca sun'),
    q('Origin Story', 'Form 6 (The Contradiction)',
      'Derived from the Spanish "peso gordo" meaning "fat peso" or "heavy peso" — a term for the Spanish silver dollar — this currency is used by Haiti today, making it one of the few currencies whose name traces back to colonial Spanish coinage.',
      'Gourde',
      ['Gourde', 'Piastre', 'Livre', 'Franc'],
      'Etymology / Name Logic',
      'The Haitian gourde (French) or goud (Creole) was introduced in 1813. The "peso gordo" was the Spanish milled dollar, widely circulated in the Caribbean. Piastre was used alongside it in colonial Haiti.',
      500, 'expert', 'Peso gordo'),
  ],
  ['Grid', 'World Currencies: What\'s in a Name?', 'Theme:Geography', 'Human', 'Facts', 'Classic', 'Mode:Focused', 'AI:Suggested'],
);

// ═══════════════════════════════════════════════════════════════════
// BATCH EXPORT
// ═══════════════════════════════════════════════════════════════════

export const batch = [topic1, topic2, topic3, topic4, topic5];

export const meta = {
  generatedAt: new Date().toISOString(),
  batchNumber: 1,
  mode: 'focused',
  totalQuestions: 150,
};
